### PR TITLE
refactor: YoStar -> Yostar only for interfaces

### PR DESCRIPTION
**Pull request by Constrat**
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9539#issuecomment-2212396015

### CODE REVIEW

**Comment by SherkeyXD** [comment]
Conflicts（x

**Comment by Constrat** [comment]
Yeah the website pr was a big one

**Comment by Constrat** [comment]
image
It's not even showing what conflicts there are

**Comment by SherkeyXD** [comment]
> image It's not even showing what conflicts there are

Now it's ok
image

**Pull request merged**
