### PR TITLE
chore: YoStarJP Sami rogue templates and tasks

### PR DESCRIPTION
**Pull request by Manicsteiner**
基本能用了，差两个template
`Sami@Roguelike@StageBoskyPassageEnter.png` ~~误入奇境，今天应该打不到了~~已完成
`Sami@Roguelike@StageFerociousPresageEnter.png` ~~不知道是啥，狂暴预兆？可能是MysteriousPresage同时的作战节点，暂时没遇到~~已完成

已知问题
开局干员招募用的 `Sami@Roguelike@Recruit.png` 只有俩字，后期遇到的作战后多个职业选一个招募则有四个字，目前添加 `Sami@Roguelike@Recruit2.png` 作为替代，在json里指定了作战后的招募 `Sami@Roguelike@GetDropSelectRecruit` 用这个template，不清楚一些不期而遇事件中可能有的招募二选一是哪个

### CODE REVIEW

**Comment by Constrat** [comment]
Merge? Or are you still working on it?

**Comment by Manicsteiner** [comment]
> Merge? Or are you still working on it?

Merge it please.

**Comment by Constrat** [comment]
As a curiosity, did you add all Encounters already? I've checked the EN wiki and it seems like I have to go through all possible encounters:P

**Comment by Manicsteiner** [comment]
> As a curiosity, did you add all Encounters already? I've checked the EN wiki and it seems like I have to go through all possible encounters:P

I just added all the events listed in the repo Kengxxiao/ArknightsGameData_YoStar, it should be complete. Search titles just like scene_ro3_sacrifice1_enter.

**Comment by Constrat** [comment]
I should reimplement it through auto updater.
Lots of work

**Pull request merged**
