### PR TITLE
feat: 战斗流程协议命令块增强

### PR DESCRIPTION
**Pull request by astr0mfly**
[#9951](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9951)

### CODE REVIEW

**Comment by Constrat** [comment]
If you can, please resolve conflicts without merging (in PRs you're free to use `git push --force`)

**Comment by zzyyyl** [comment]
改改文档 docs/zh-cn/protocol/copilot-schema.md

**Comment by astr0mfly** [comment]
> If you can, please resolve conflicts without merging (in PRs you're free to use `git push --force`)

看起来是门禁问题，我这边在修。

**Comment by astr0mfly** [comment]
> 改改文档 docs/zh-cn/protocol/copilot-schema.md

写好了

**Pull request merged**
