### PR TITLE
feat: IS4 EN + Auto Resource Updater roguelike encounter

### PR DESCRIPTION
**Pull request by Constrat**

### CODE REVIEW

**Comment by Constrat** [comment]
@Manicsteiner oof conflicts. I managed to tweak the resource updater to implement the encounters (lots of duplicates I removed all of them). I'll just revert my JP commit. If you want / can, have a look at the resource updater to see if there any missed encounters

**Comment by HX3N** [comment]
@Constrat 
If there are any spaces, YoStarKR doesn't recognize it, so I've made the necessary adjustments.
Should I upload the modified tasks.json for this PR to #8492? Or would it be better to upload it here?
I'll go ahead and upload the file here for now. If uploading it here is preferable, I'll close #8492.

[tasks.json](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14508411/tasks.json)

**Comment by Constrat** [comment]
There's already an ocrreplace for the entire korean replace tasks. Adding / removing spaces shouldn't change anything iirc.

**Comment by HX3N** [comment]
```            [
                "(\\s|\\$|\\(|\\)|\\.|\"|/|'| | |—|_|-|=|,)",
                ""
            ],
```


After removing the spaces through the above process, it meant that there should be no spaces in ocrReplace when converting from Korean to Chinese.

```
            [
                "밥의 잡화점",
                "鲍勃杂货店"
            ],
```


In the case of the following ocrReplace, recognition does not occur because the spaces between Korean characters have already been removed above.

**Comment by Constrat** [comment]
The I'll also revert the KR, it's just faster. I'll leave the resource updater as-is, if you want to use it.

**Comment by HX3N** [comment]
YoStarKR, for some reason unknown to me, removes spaces first before performing ocrReplace. Therefore, even after updating the file with Resource Updater, an additional step is needed to remove the spaces in ocrReplace.

What I mentioned earlier was that the resource updater worked fine, but spaces needed to be removed, and I have made the necessary changes to address this.

For now, I have uploaded tasks.json to the PR with only spaces removed from the tasks.json where the resource updater has been applied.

I took a little longer to leave comments because I'm not proficient in English.

**Comment by Constrat** [comment]
No worries, just check the result of the resource updater if you run it. There could be up to 12 duplicates.

**Comment by Constrat** [comment]
I think I managed to remove all dupes. If you guys have time to check if there are all encounters that would be great.

**Comment by Manicsteiner** [comment]
@ABA2396 考虑到 #7904 在encounter.json添加了一些选项的名称，是否也需要为这些选项名称添加OCR replace？

**Comment by ABA2396** [comment]
> @ABA2396 考虑到 #7904 在encounter.json添加了一些选项的名称，是否也需要为这些选项名称添加OCR replace？

这些其实都还没用上，实际选的还是看的抗干扰值和choose

**Comment by Constrat** [comment]
@ABA2396 MAA crashes unexplainably when it has to ocrReplace inside the trader store.
Could this be because there are `2637 / 4 = 660` possible replaces?
I also noticed that IS4 added A LOT OF options that don't seems trader "items" such as `Not earning a Perfect will +2 Collapse value` -> `非完美作战增长2坍缩值`. How can this be an item that needs to be ocrReplaced?

**Comment by Constrat** [comment]
@Manicsteiner @HX3N Did you guys touch any regex for the `RoguelikeTraderShoppingOcr`, because I made some big changes to ResourceUpdater, removing 50 not buyable items.
If you did make changes, I suggest deleting all IS4 items (commit ID: eca4f9561216235e4d358cb176665604aa0bd58d), applying the resource updater, and checking the diff view for "modified" regexes. Sorry for all these troubles, but the AutoUpdater ran a weekly earlier than the IS4 release, so I couldn't if anything was correct or not.

**Comment by Constrat** [comment]
I hate IS adaptation 🙄

**Comment by Constrat** [comment]
Of course this happens now. I started noticing that just like for the korean version, probably because of the background coloring spaces ` ` are never detected correctly.

`asst::WordOcr [{ AProfitable Plan:`

**Comment by swablueme** [comment]
> Of course this happens now. I started noticing that just like for the korean version, probably because of the background coloring spaces ` ` are never detected correctly. This never happened in IS3
> 
> `asst::WordOcr [{ AProfitable Plan:`
> 
> Should I just follow korean's solution, removing all spaces from the list and adding a ocrReplace " " -> "" Open to suggestions.
> 
> ```json
>             [
>                 "A Profitable Plan",
>                 "有利可图"
>             ],
> ```
What about something like this? Note it makes nearly everything unreadable
image
image

**Comment by HX3N** [comment]
After IS4 was released, I deleted the items ```RoguelikeTraderShoppingOcr``` and ran Resource Update.
I checked and found that many items have been reduced.

Can I do PR? The commit is 0d92f1b3ceff2d2b5344249fff2ff10ecf17568e.

**Comment by Constrat** [comment]
@swablueme unfortunately I don't think it's just for certain encounters.
This also happened for "Useless Item", where the space was omitted. So I'm pending heavily on the Korean solution.

**Comment by HX3N** [comment]
> That's should be the correct amount. What should have been removed are the starting Squad names, and the "effects"

I checked and I moved the squad to the top of the ```Roguelike Trader Shopping Ocr```
I've also deleted the squad. (8dac8bed58fa5da6a877b53bc4334da2e34074c6)

**Comment by Constrat** [comment]
To make sure that's all you could completely remove encounter OCR, runthe updater. And after that see if there are differences. Write che differences down, and remove the other unnecessary, in case you want to. I'm saying all this because if there are too many ocrReplqces it seems MAA crashes, especially on the trader store

**Comment by Lancarus** [comment]
> @ABA2396 MAA crashes unexplainably when it has to ocrReplace inside the trader store. Last line before crash shows nothing. (same for gui.log)
> 
> ```python
> [2024-03-07 19:57:29.850][TRC][Pxce48][Txc2b4] asst::WordOcr [{ Survey Equipment: [ 432, 36, 110, 14 ], score: 0.964963 }, { Delight: [ 634, 42, 57, 23 ], score: 0.997786 }, { Support Mr. Boom: [ 225, 44, 134, 20 ], score: 0.998937 }, { Prospective Investment System: [ 9, 47, 190, 14 ], score: 0.964943 }, { Maintenance Device: [ 432, 57, 124, 14 ], score: 0.981454 }, { Pause investment: [ 8, 88, 85, 13 ], score: 0.982173 }, { XE: [ 478, 106, 72, 42 ], score: 0.139409 }, { Current Balance: [ 102, 135, 96, 14 ], score: 0.962222 }, { 010: [ 56, 159, 136, 61 ], score: 0.997814 }, { Price: [ 367, 174, 35, 18 ], score: 0.997492 }, { Price: [ 576, 175, 30, 15 ], score: 0.998708 }, { Price: [ 781, 173, 32, 19 ], score: 0.998353 }, { 8: [ 369, 190, 29, 34 ], score: 0.996680 }, { 12: [ 532, 189, 74, 37 ], score: 0.999068 }, { 8: [ 781, 191, 29, 34 ], score: 0.999241 }, { Guard Rec.Voucher: [ 20, 256, 144, 17 ], score: 0.959850 }, { Specialist Rec.Voucher: [ 227, 257, 171, 17 ], score: 0.980451 }, { Lakebed Aegis: [ 433, 257, 107, 17 ], score: 0.978489 }] by OCR Pipeline , cost 392 ms
> ```
> 
> Could this be because there are `2637 / 4 = 660` possible replaces? If this really is because of the too many replaces needed, this is not looking good. I also noticed that IS4 added A LOT OF options that don't seem trader "items". How can this be an item that needs to be ocrReplaced?
> 
> Examples:
> 
> ```json
> "Not earning a Perfect will +2 Collapse value",
> "非完美作战增长2坍缩值"
> ```
> 
> ```json
> "Originium Ingots, Life Points, and Hope are doubled",
> "源石锭生命希望变为2倍"
> ```
> 
> They all come from image
> 
> cc @Lancarus

The "item" you show don't need to be replaced. Just replace the name of goods in shop？Seen in shopping.json
image
Just the “name” need to be ocrreplaced. And “effect” is for helping you recall the effect of the goods to range their purchase priority."No" is the number in [prts.wiki](https://prts.wiki/w/%E6%8E%A2%E7%B4%A2%E8%80%85%E7%9A%84%E9%93%B6%E5%87%87%E6%AD%A2%E5%A2%83/%E4%BB%AA%E5%BC%8F%E7%94%A8%E5%93%81%E7%B4%A2%E5%BC%95). And  some of the goods have 3 upgrades with suffix “-α”，"-β"，“-γ”, you can only replace the common part of them.

**Comment by Constrat** [comment]
All the items in ocrReplace come from the auto updater, and it seems "items" does not only have relics. I managed to narrow down the number of "other things" form that list.
Maybe I can completely overhaul this, by just selecting the names that are present in the shopping.json list.

**Comment by Constrat** [comment]
Let's try again, this time with the updated Auto Resource Updater. Github finding conflicts where there are none.

**Pull request closed without merging**
