### PR TITLE
chore: dont close issue too early

### PR DESCRIPTION
**Pull request by AnnAngela**
晒足一百八十天.jpg

### CODE REVIEW

**Comment by Constrat** [comment]
I feel like 180 is really a lot.
Considering we release a beta or a main release every week or two. Issues become old fast with 180 days. And let's be honest. All the enhancement issues are useless considering they are like product managers that have no idea on how to code asking us to implement ChatGPT AI in MAA, or allowing MAA to control the house light or other things like that.

Personally: If you want to see a change, PR it yourself. Otherwise, if you think it's a necessary change, just put it under BUG.

**Comment by status102** [comment]
maybe 90d or 60d？

**Comment by status102** [comment]
有个问题是，bot发完之后那个警告，不会影响issue的未更新时间吗

**Comment by Constrat** [comment]
No, the checker, skips bot messages.

**Comment by AnnAngela** [comment]
@status102 我觉得 90 天吧会好些

@Constrat I think that 30d is too short, maybe 90d is better :) changed in 94c9ea2

**Pull request merged**
