### PR TITLE
perf: duplicates templates from I.S.

### PR DESCRIPTION
**Pull request by Constrat**
While working on the tools ignore templates I noticed that the same template was being used 3 different times with 3 different names.
This doesn't make sense. So:
- Changed the name of the base template
- Added "template": "xxx.png" where needed (All the StageTraderRefresh tasks)
- Removed duplicate Confirm template

### CODE REVIEW

**Comment by Constrat** [comment]
Logically this shouldn't have changed anything, but testing is needed.

**Comment by Constrat** [comment]
Something weird happened, it's correctly identifying the template and it's even clicking in the correct position but the confirm button doesn't appear lol. 
image

**Review by Lancarus — APPROVED** [review]

**Comment by Constrat** [comment]
Hold up, I think some fixes are needed.

**Comment by Constrat** [comment]
Even inverting the postDelay it will still click the refresh and then the item lol.

**Comment by Constrat** [comment]
@Lancarus LMAOO
I finally found out why. On the CN client the Refresh button fucking disappears, on the EN it does fucking not.

**Comment by Constrat** [comment]
No idea on how to fix this. Since the hardcoded cpp ProcessTask takes precedence over the next field of Roguelike@TraderRandomShopping

**Comment by Daydreamer114** [comment]
> While working on the tools ignore templates I noticed that the same template was being used 3 different times with 3 different names. This doesn't make sense.

This happens because different themes were wroten by different people. If we are not aware of the template is already exist (of course we don't want to spend time to check on every template), we will create a new one.
Good luck with testing XD.

**Comment by Constrat** [comment]
At least it's a global issue. Soon™ will get the update hopefully

**Comment by status102** [comment]
> @Lancarus LMAOO I finally found out why. On the CN client the Refresh button fucking disappears, on the EN it does fucking not.
> 
> @HX3N @Manicsteiner Check your clients. As of now IS Trader is broken. On EN it's working because of a typo on my end: [`dev`/resource/global/YoStarEN/resource/template/Sami@Roguelike@StageTraderRefresh.png.png](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/global/YoStarEN/resource/template/Sami%40Roguelike%40StageTraderRefresh.png.png?rgh-link-date=2024-08-26T15%3A33%3A11Z)
> 
> This is crazy.
> 
> CN
> vs
> 
> EN

calm down guy, it's just because you haven't activated this.

**Comment by status102** [comment]
> ```
>         // 这里仅点一下收藏品，原本的 ProcessTask 还会再点一下，但它是由 rect_move
>         // 的，保证不会点出去 即 ProcessTask 多点的那一下会点到不影响的地方 然后继续走 next 里确认
>         // or 取消等等的逻辑
> ```
> 

I discovered that and forgot whether I changed it or not.

**Comment by HX3N** [comment]
> calm down guy, it's just because you haven't activated the rule of showing refresh button.

Seems like the refresh button that appears when selecting an item has disappeared.

<details><summary>img</summary>

Screenshot_2024 08 27_15 12 16 577
Screenshot_2024 08 27_15 12 20 343

화면 캡처 2024-08-27 152100
화면 캡처 2024-08-27 152122

</details>

**Comment by status102** [comment]
> > calm down guy, it's just because you haven't activated the rule of showing refresh button.
> 
> Seems like the refresh button that appears when selecting an item has disappeared.
> 
> img

omg, there must be a bug here

**Comment by status102** [comment]
手滑不小心关了（

**Comment by Constrat** [comment]
> > Seems like the refresh button that appears when selecting an item has disappeared.
> > 
> > img
> 
> omg, there must be a bug here

Not surprised Yostar fucked it up :)

**Comment by Constrat** [comment]
@HX3N Honestly comparing CN and Global, the CN seems just more tweaked so I really hope it's an update that will come to us. But Sami should have ended, no? They already added the last expansion with the 4th ending so I don't think it's going to be an update with that. Maybe with Sarkaz?

But checking the file history for RoguelikeShoppingTaskPlugin it seems like this issue has never been addressed, so maybe it's not something we will receive and it's going to remain an inconsistency (It would really be Yostar's fault XD)

**Comment by Constrat** [comment]
I have an idea, since the score is "only" 0.89, maybe locking it to >0.9 will stop it from working when the item is being purchased, making the ProcessTask work correctly, and hopefully when the item doesn't need to be bought the score is higher? hope.png

**Comment by Constrat** [comment]
Unlucky, the same: 0.893497

**Comment by Constrat** [comment]
Ok actually it's somehow working, it's very wonky, meaning it will click the refresh when it shouldn't but luckily it will repeat the task and the second time it will confirm the purchaese. It will do so until it will refresh correctly and then to it again... I'm considering this a win.
@HX3N @Manicsteiner I'm merging, check your clients later, as I tried removing the correct tasks and removing the templates but Sami@Roguelike@StageTraderRefresh was missing in both KR and JP meaning that this issue was not present at all (same for EN but it was a typo on my end) now since we are using the same template as the other IS it will start working (very wonky for global)

**Pull request merged**
