### PR TITLE
feat: 自动战斗新增战斗列表选项（异形UI不支持）

### PR DESCRIPTION
**Pull request by status102**
丑了吧唧的UI，算得上是help wanted了
E64~~_%8YXMX%ARC)RC %~W

#5695

### CODE REVIEW

**Comment by Constrat** [comment]
@status102 don't worry about the Qodana checks, it has been giving errors every time. 
If all the others are green there's nothing to worry about

**Comment by status102** [comment]
> @status102 don't worry about the Qodana checks, it has been giving errors every time. If all the others are green there's nothing to worry about

thanks,I don't worry about the Qodana check, it's not a matter. I'm worry about another thing. Only the issue check was triggered at first. After I rebased it, it looks good. But I don't know why it didn't trigger all checks.

**Comment by ABA2396** [comment]
qodana 没有你私人仓库的扫描权限，只有在主仓库下点分支才能扫）

**Comment by status102** [comment]
> qodana 没有你私人仓库的扫描权限，只有在主仓库下点分支才能扫）

不是qodana的问题，而是rebase之前只触发了issue-check，给我干懵了

**Comment by MistEO** [comment]
开始按钮是不是放下面好点，因为其他界面也都是在左下方或者右下方，统一一点（

不常修改的 checkbox 可以考虑放 settings 里？

**Comment by status102** [comment]
HMF(BR1HEXL$HTHRR173)9N
(A$ WIWG{F ) PWYZ{N4A2L

**Comment by status102** [comment]
image

微调了一下Margin，右边加了一段文本

**Pull request merged**
