### PR TITLE
chore: Add OCR Replace ["슈", "黍"],

### LINKED ISSUE #10021: Infrast: operator and skill separate string failed on training room
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

During the Infrast task, MAA repeatedly fails to separate the operator and skill in the training room (so, entering and exiting  repeatedly).
After adding logging post-ocrReplace, I checked the logs and found that in the CN, it is converted with `\n`, but there is no `\n` in the KR. I don't know how to resolve this on my own.

Are other servers like this too?

### Version

Resource Version: 회서리
UI Version: Debug
Core Version : Debug

### Log files

| 진행도 58% |  Progress 58% | 川练进度 58% |
| -- | -- | -- |
[슈] 우거진성쇠지 |  [Shu] Samsara | [黍] 离离枯荣 |

``` python
[2024-08-02 03:41:08.087][TRC][Pxea60][Txe9a8] asst::WordOcr [{ 진행도58%: [ 0, 0, 150, 28 ], score: 0.999778 }] by OCR Rec , cost 39 ms
[2024-08-02 03:41:08.122][TRC][Pxea60][Txe9a8] asst::WordOcr [{ [슈]우거진성쇠지+: [ 0, 0, 280, 37 ], score: 0.835495 }] by OCR Rec , cost 35 ms
[2024-08-02 03:41:08.124][INF][Pxea60][Txe9a8] asst::InfrastTrainingTask::analyze_status OCR text:  슈우거진성쇠지+
[2024-08-02 03:41:08.124][ERR][Pxea60][Txe9a8] asst::InfrastTrainingTask::analyze_status Separate string failed.
[2024-08-02 03:41:08.124][TRC][Pxea60][Txe9a8] ready to sleep 500
[2024-08-02 03:41:08.626][TRC][Pxea60][Txe9a8] end of sleep 500
[2024-08-02 03:41:08.626][TRC][Pxea60][Txe9a8] asst::InfrastAbstractTask::on_run_fails | enter
[2024-08-02 03:41:08.626][TRC][Pxea60][Txe9a8] asst::ProcessTask::_run | enter
```

``` python
[2024-08-02 03:40:15.316][TRC][Pxc230][Txe24c] asst::WordOcr [{ 川练进度29%: [ 0, 0, 150, 28 ], score: 0.952392 }] by OCR Rec , cost 118 ms
[2024-08-02 03:40:15.359][TRC][Pxc230][Txe24c] asst::WordOcr [{ [佩佩]时光震荡: [ 0, 0, 284, 37 ], score: 0.932888 }] by OCR Rec , cost 43 ms
[2024-08-02 03:40:15.360][INF][Pxc230][Txe24c] asst::InfrastTrainingTask::analyze_status OCR text:  佩佩
时光震荡
[2024-08-02 03:40:15.368][TRC][Pxc230][Txe24c] The best match is { name: InfrastTrainingLevel1.png, matched: [ 159, 551, 96, 28 ] } InfrastTrainingLevel1.png
[2024-08-02 03:40:15.368][INF][Pxc230][Txe24c] asst::InfrastTrainingTask::level_analyze level has been set to  1
[2024-08-02 03:40:15.368][TRC][Pxc230][Txe24c] asst::ProcessTask::_run | enter
```

### Screenshots

<details><summary> image </summary>

Screenshot_2024 08 02_04 01 52 440
</details>

### Anthing else?

_No response_

### PR DESCRIPTION
**Pull request by Daydreamer114**
fix #10021

### CODE REVIEW

**Comment by Daydreamer114** [comment]
@HX3N Try adding this to your maa and merge if works well

**Comment by Constrat** [comment]
For very short (one chars) it's usually pretty dangerous to leave that much space. Anything that uses CharsNameReplace could just replace that char as "Shu"

**Comment by Daydreamer114** [comment]
> For very short (one chars) it's usually pretty dangerous to leave that much space. Anything that uses CharsNameReplace could just replace that char as "Shu"

All other languages will be replaced into Chinese, then analyse in cpp, am I right?

**Comment by Constrat** [comment]
That's usually how it works, so we need to be very careful with what should get replaced.

**Comment by Daydreamer114** [comment]
> That's usually how it works, so we need to be very careful with what should get replaced.

well in his/her log, it seems that 슈 can be directly recognized as "슈"

**Comment by HX3N** [comment]
> @HX3N Try adding this to your maa

I found out that the `\\`s in `CharsNameOcrReplace` was the problem 🤣

**Pull request closed without merging**
