### PR TITLE
feat: Support Base for the JP client

### PR DESCRIPTION
**Pull request by ABA2396**
Thanks to `ajk#0579` (JP client)

### CODE REVIEW

**Comment by MistEO** [comment]
@wallsman Hi, could you help us to test it? [download](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/3472532897)

**Comment by wallsman** [comment]
Thank you for contacting us.
I have tried the following options.

Please check if it is as expected as the actual video is attached.
image

Movie
https://vimeo.com/771336113

**Comment by wallsman** [comment]
@MistEO 

GuyLog
2022/11/16 4:37:59 エミュレータ接続中……
2022/11/16 4:38:08 動作中……
2022/11/16 4:38:08 タスク開始：Infrast
2022/11/16 4:38:21 現在の施設：Mfg 0
2022/11/16 4:38:43 現在の施設：Mfg 0
2022/11/16 4:39:58 現在の施設：Mfg 1
2022/11/16 4:40:09 現在の施設：Mfg 2
2022/11/16 4:40:28 現在の施設：Mfg 3
2022/11/16 4:40:40 現在の施設：Mfg 4
2022/11/16 4:41:04 現在の施設：Trade 0
2022/11/16 4:42:25 現在の施設：Control 0
2022/11/16 4:43:01 現在の施設：Power 0
2022/11/16 4:43:22 現在の施設：Power 1
2022/11/16 4:43:35 現在の施設：Power 2
2022/11/16 4:43:53 現在の施設：Reception 0
2022/11/16 4:44:59 現在の施設：Office 0
2022/11/16 4:45:24 現在の施設：Dorm 0
2022/11/16 4:45:44 現在の施設：Dorm 1
2022/11/16 4:46:02 現在の施設：Dorm 2
2022/11/16 4:46:22 現在の施設：Dorm 3
2022/11/16 4:46:44 タスク完了：Infrast
2022/11/16 4:46:44 すべてのタスクが完了しました！
2022/11/16 5:04:44 

Doing log
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10016498/asst.bak.log)

**Comment by MistEO** [comment]
It seems that there are some problems with swiping, but this is a common problem in the beta version, not only in the JP client, we will fix it in the next version.

**Pull request merged**
