### PR TITLE
Localization fix for ko-KR

### PR DESCRIPTION
**Pull request by GyeRyak**
Social point shop default blacklist and whitelist not work properly due to the space, so removed it.
And slightly trimmed some other localizations.

### CODE REVIEW

**Comment by liuyifan-eric** [comment]
> Social point shop default blacklist and whitelist not work properly due to the space

Can you specify this? I personally think it should be a bug

**Comment by GyeRyak** [comment]
Yes, when the word containing whitespace like previous default "즉시 완료 허가권", OCR cannot detect it properly.
After I removed whitespaces, MAA works as intended.

> > Social point shop default blacklist and whitelist not work properly due to the space
> 
> Can you specify this? I personally think it should be a bug
> 
> Do you mean the items should have whitespace but the OCR cannot handle them?

**Comment by MistEO** [comment]
I think this problem can be solved by adding `CreditShop-ProductName` - `ocrReplace` to YostarKR.

**Review by MistEO — APPROVED** [review]
LGTM. But another PR #4940 also changed a lot of translated text, maybe causing conflicts. We need to wait until #4940 is merged before merging this.

Thx-ld

**Pull request merged**
