### PR TITLE
Release v5.6.0-beta.1

### PR DESCRIPTION
**Pull request by ABA2396**

### CODE REVIEW

**Comment by ABA2396** [comment]
怎么都堆了 241 个 commit 了）

**Comment by Daydreamer114** [comment]
不急的话麻烦等一下#10279 ）

**Comment by Constrat** [comment]
We are in a hurry. RA#2 has already been released. Users are asking for it.

**Review by Constrat — APPROVED** [review]
[6b89a87](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10271/commits/6b89a87a023652dd527be7edf06037ecb61c220e) is needed as withtout it smoke-testing is dead

**Comment by Daydreamer114** [comment]
it's ready for merge and already tested. a few minutes.

**Pull request merged**
