### PR TITLE
fix: Fight Task Adverse Start YostarEN

### PR DESCRIPTION
**Pull request by Constrat**
Added the StartButton3.png to CN/template and EN/template, modified CN tasks.json to implement new StartButton3 task.
fix for #5060 

From log:
asst::TemplResource::get_templ lazy load StartButton3.png match_templ | StartButton3.png score: 0.972579 rect: [ 1038, 371, 131, 272 ] roi: [ 1000, 350, 220, 340 ]

(second try because github hates me, again sorry for the trouble)

### CODE REVIEW

**Comment by MistEO** [comment]
StartButton2-Adverse should be better?

**Comment by Constrat** [comment]
Sure! I'll get to it by today.

**Comment by Constrat** [comment]
I prefer it without the dash, makes it look more clean
Also I didn't like the "StartButton2-NormalTryAgain". I think the dash was in the wrong place so I decided to remove it completely o.o

**Comment by MistEO** [comment]
Do not change the name of the existing tasks, other overseas clients and the logic in the code depend on these task names. Added tasks are up to your liking. XD

**Comment by MistEO** [comment]
https://github.com/search?q=org%3AMaaAssistantArknights%20startbutton2&type=code

**Comment by Constrat** [comment]
I've completely forgot about that.
StartButton2Normal -> StartButton2 as it was before
StartButton2Adverse stays as is because it's a new task correct?

**Comment by MistEO** [comment]
> I've completely forgot about that.
> StartButton2Normal -> StartButton2 as it was before
> StartButton2Adverse stays as is because it's a new task correct?

Sure.

**Comment by MistEO** [comment]
Your commits are a bit messy, I will squash them.

**Comment by MistEO** [comment]
Thx-ld

**Pull request merged**
