### PR TITLE
feat: Templates for new GUI (Siege) and fix #8503

### LINKED ISSUE #8503: 好友列表界面改动，访问好友获得信用功能出现图像识别异常
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

如图所示，游戏对好友列表的界面进行了改动，软件的图像识别出错，直接跳过访问好友步骤
image

### Version

Resource Version: 水晶箭行动
UI Version: v5.1.0
Core Version: v5.1.0

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14524214/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14524216/gui.log)

### 截图

_No response_

### 还有别的吗？

_No response_

### PR DESCRIPTION
**Pull request by Lemon-miaow**
Fix #8503 #8507 #8509
May need more testing.

### CODE REVIEW

**Comment by Constrat** [comment]
Looks good to me, but on a personal note I would suggest changing `Siege` to something like `Rainbow` or even better `Rainbow6` (Or `RainbowSix`), because `Siege` is the official translation for `推进之王`

**Comment by Lemon-miaow** [comment]
> Looks good to me, but on a personal note I would suggest changing `Siege` to something like `Rainbow` or even better `Rainbow6` (Or `RainbowSix`), because `Siege` is the official translation for `推进之王`

I was thinking `Siege` mainly because the Siege in RainbowSix:Siege translates to 彩虹六号：围攻（

**Comment by Constrat** [comment]
Well, let's just hope they will never release a `推进之王` themed interface XD

**Comment by Lemon-miaow** [comment]
> Well, let's just hope they will never release a `推进之王` themed interface XD
> 
> 
> 
> Did you manage to test all the interfaces?

I tried it just now and changed the roi. It works for me, but I'm not sure if it works as well for others.

**Comment by Constrat** [comment]
If you tested on 1280x720, it should work for the majority, as it seems themes are not resolution-bound

**Comment by Lemon-miaow** [comment]
> Well, let's just hope they will never release a `推进之王` themed interface XD
> 
> 
> 
> Did you manage to test all the interfaces?

Includes other interfaces.

**Comment by Constrat** [comment]
Thank you very much for your **first** contribution!

**Comment by Lemon-miaow** [comment]
> Thank you very much for your **first** contribution!

Thanks！

**Pull request merged**
