### PR TITLE
feat: WpfGui新增 肉鸽设置-中止行为等待至本次战斗结束后

### LINKED ISSUE #1961: 建议肉鸽增加“本局结束后停止”的功能
### 说说你遇到的问题？

挂机时离开电脑等到需要看挂机进度时，还需盯着屏幕等待本局结束，手动点击停止。

### 有什么好的想法？

建议增加“本局结束后停止”的功能，不会影响本局对战，人也无需盯着对战进度。

### 其他内容

_No response_

### PR DESCRIPTION
**Pull request by status102**
- close #1961

~~顺带移除了肉鸽battle里面从status()读数据的部分~~
~~顺带移除了status()的肉鸽主题数据，以及在肉鸽battle的缓存了一下精英数据(?)~~
- ↑移动至 #6646

image

image

### CODE REVIEW

**Comment by status102** [comment]
#1961

**Review by Lancarus — APPROVED** [review]

**Comment by Constrat** [comment]
For translation purposes. The STOP will happen when you completely conclude an exploration (beating the final boss) or just losing an exploration will count?

**Comment by status102** [comment]
> For translation purposes. The STOP will happen when you completely conclude an exploration (beating the final boss) or just losing an exploration will count?

It's a good question. I haven't tested them.

**Comment by Constrat** [comment]
Because I don't understand if I should translate all this to `Stop after successfully ending the exploration.`
Or something else more _generic_

**Comment by Constrat** [comment]
> It's a good question. I haven't tested them.
 Testing the successful exploration ending will be a pain in the ass, even at lower difficulties, but I'm pretty sure there's a flag if the exploration is abandoned or is concluded successfully

**Comment by status102** [comment]
> Because I don't understand if I should translate all this to `Stop after successfully ending the exploration.` Or something else more _generic_

It doesn't work when exploring other nodes. At the same time, it does not pay attention to whether an exploration has been completed。

**Comment by Constrat** [comment]
> It doesn't work when exploring other nodes. At the same time, it does not pay attention to whether an exploration has been completed。

So at the first "Exploration lost / abandoned" it will stop? But... Isn't this the same as 
image

**Comment by Lancarus** [comment]
I think he means when you click "stop" button during a combat, the script will keep running until this combat is finish. Not
the whole exploration?

**Comment by Constrat** [comment]
That's completely different then... Also, wouldn't this break all the consistency as to what STOP is?

**Comment by Constrat** [comment]
`Stops after clearing the combat` something like this should work.

**Comment by status102** [comment]
> That's completely different then... Also, wouldn't this break all the consistency as to what STOP is?

maybe add an emergency stop? a final stop? ¯\_(ツ)_/¯

It seems that it will make a bigger broke in MaaCore. This bothers me all day.

**Comment by Constrat** [comment]
Yeah that's what I was thinking about consistency. Stop is no longer stop...
Usually the panic button is the STOP (Even if in some modes it becomes unavailable and you can't stop it like in the GACHA mode or the OPERATOR identification)

**Comment by status102** [comment]
Add a new button called `Wait And Stop` for this mode ?

**Comment by Constrat** [comment]
> Add a new button called `Wait And Stop` for this mode ?

That might be an idea but... How would the UI look? There is not that much space left after all. 
It could be placed instead of the tickbox `RoguelikeDelayAbortUntilCombatComplete`?

**Comment by Lancarus** [comment]
> Add a new button called `Wait And Stop` for this mode ? Click it then the common STOP button will show.

Why not change the text “stop” button show？Or show a tip after click it？

**Comment by Constrat** [comment]
Wait but going back to the idea of "Stops after the combat" the MAIN STOP button will still be available and usable at any time.

**Comment by status102** [comment]
sorry for wrong edit

New button(Wait And Stop will covered the common `STOP`. Click it and it disappears. Then, you can click the old STOP button.

**Comment by Constrat** [comment]
> sorry for wrong edit

No worries

**Comment by Constrat** [comment]
> New button(Wait And Stop will covered the common `STOP`. Click it and it disappears. Then, you can click the old STOP button.

And to make ti reappear? I feel like it needs to be a "switch" which can be toggled on and off, on-the-go.
If I start an exploration and it's a combat, till the last second I need to be able to reach this switch to let MAA automatically STOP after clearing the stage no?

**Comment by zzyyyl** [comment]
有没有可能直接把这个按钮放到肉鸽的高级设置里（

**Comment by status102** [comment]
> And to make it reappear? I feel like it needs to be a "switch" which can be toggled on and off, on-the-go.
> If I start an exploration and it's a combat, till the last second I need to be able to reach this switch to let MAA automatically STOP after clearing the stage no?

New Stop only appears in a combat (of cource need to active the switch)

**Comment by status102** [comment]
> 有没有可能直接把这个按钮放到肉鸽的高级设置里（

你是说新停止按钮？藏太深了，至少要1次点击+1次滑动才能抵达

**Comment by Constrat** [comment]
> New Stop only appears in a combat (of cource need to active the switch)

Ok so in the advanced settings the switch becomes: "Show wait & stop button", if toggled on, the "new" button will appear instead of the usual STOP. If clicked, it will Wait & Stop, if clicked again it will toggle off, revealing the normal "STOP"?

**Comment by Constrat** [comment]
> 有没有可能直接把这个按钮放到肉鸽的高级设置里（

image
This was a suggestion(?)

**Comment by status102** [comment]
> Ok so in the advanced settings the switch becomes: "Show wait & stop button", if toggled on, the "new" button will appear instead of the usual STOP. If clicked, it will Wait & Stop, if clicked again it will toggle off, revealing the normal "STOP"?

yep.

**Comment by status102** [comment]
Do you think the switch text needs to be adjusted?

Now:
中止行为等待至战斗结束后
Stops after clearing the combat

**Comment by Constrat** [comment]
I was thinking about this? `Show wait & stop button` because now the switch doesn't directly do the wait and stop, but it will show the button to do it? Does this make sense?

**Comment by status102** [comment]
All are OK, `Stops after clearing the combat` describes function, `Show wait & stop button` describes behavior.
I prefer the former (x

**Comment by Constrat** [comment]
image
Either fit correctly. It's your choice :)

**Comment by status102** [comment]
大概像这样（图3有点bug

)NR BVA~R6LTBH466HO34

)`4 67~A}~IG~ZHOR_5H GX

L_$}V3Z` 3 3KZ6)Y7}D0ZE

**Comment by Constrat** [comment]
Looks good.

**Review by zzyyyl — APPROVED** [review]
This approval applies to changes related to MaaCore.

**Comment by MistEO** [comment]
改动太多了，没找到新逻辑在哪_(:з」∠)_一个PR最好只干一件事

**Comment by status102** [comment]
> 改动太多了，没找到新逻辑在哪_(:з」∠)_一个PR最好只干一件事

本来是想着做到Core，然后把肉鸽battle的Status缓存全拆了，结果发现会打乱掉need_exit的逻辑。就把逻辑做回Gui了，缓存拆了感觉更好就没恢复原样了

**Comment by status102** [comment]
> 改动太多了，没找到新逻辑在哪_(:з」∠)_一个PR最好只干一件事

我拆PR吧

**Comment by status102** [comment]
@MistEO 已rebase

**Review by MistEO — APPROVED** [review]

**Pull request merged**
