### PR TITLE
fix: 界面更新后悖论模拟无法开始战斗

### LINKED ISSUE #10421: 悖论模拟UI更新后无法正常进行自动战斗
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

如题

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

@

### 配置信息

@

### 截图或录屏

_No response_

### 还有别的吗？

_No response_

### PR DESCRIPTION
**Pull request by ABA2396**
cc @MaaAssistantArknights/global-support-team 
官服这个界面的 UI 在更新之后改了，我先把其他服的 roi 保留了，到时候更新的话还得补下对应的图
MuMu12-20240903-161220
MuMu12-20240903-161224
MuMu12-20240903-161226
BattleStartSimulation

close #10421

### CODE REVIEW

**Comment by Constrat** [comment]
@ABA2396 Isn't just the white arrow with blue background enough?
image

**Comment by ABA2396** [comment]
> @ABA2396 Isn't just the white arrow with blue background enough? 

The default template matching is color weakness, maybe it will think that the two are the same. I will see if HSV can do it. But in any case, need modify it later

**Comment by Constrat** [comment]
If it's a bother, no worries. It was just to reduce the template requirement and try to reduce sizes, since the test will change depending on the client :P

**Review by Constrat — APPROVED** [review]

**Comment by Constrat** [comment]
Will the global tasks inherit the HSV manipulation?

**Comment by ABA2396** [comment]
> Will the global tasks inherit the HSV manipulation?

It will.)

**Review by SherkeyXD — APPROVED** [review]

**Review by Constrat — APPROVED** [review]

**Pull request merged**
