### PR TITLE
 docs: update and refactor KR docs

### PR DESCRIPTION
**Pull request by HX3N**
It's taking a really long time.

There's probably no problem... right?

### CODE REVIEW

**Comment by HX3N** [comment]
@ABA2396 

<details><summary>image</summary>

Image
</details>

```markdown
![Image](https://github.com/HX3N/MaaAssistantArknights/assets/128385247/95b7100a-97e1-4c78-bfce-56cdac7712e7)
```

I have modified the image.
Is it okay that the image link is directed to my repository?

**Comment by ABA2396** [comment]
No problem.

The group discussed the idea of putting the images in a unified folder when we refactor it later, so we'll see how it goes. ~~If it does get refactored~~

**Comment by ABA2396** [comment]
Please check your email as I have sent you a membership invitation. Once accepted, you'll be able to create new branches and push changes directly to the repository without the need to fork and modify separately.

**Comment by HX3N** [comment]
Now there won't be any strange parts left, right...?
Why is it that every time I check to make sure nothing's wrong, I end up finding one strange thing after another...   
I thought I checked it thoroughly..   

I'll double-check one last time before merging

**Pull request merged**
