### PR TITLE
Fix: 台服幹員W無法識別問題

### PR DESCRIPTION
**Pull request by Arcelibs**
Update tasks.json

image

### CODE REVIEW

**Comment by Arcelibs** [comment]
[2023-08-12 23:59:15.420][INF][Px1898][Txd18] load D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template
[2023-08-12 23:59:15.436][ERR][Px1898][Txd18] Templ load failed, file not exists D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template\Mizuki@Roguelike@GetDropCompleted.png
[2023-08-12 23:59:15.436][TRC][Px1898][Txd18] asst::TemplResource::load | leave, 16 ms
[2023-08-12 23:59:15.436][ERR][Px1898][Txd18] TaskData load failed, path: D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\tasks.json , templ dir: D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template
[2023-08-12 23:59:15.436][TRC][Px1898][Txd18] asst::ResourceLoader::load | leave, 6473 ms

啊?

**Comment by Constrat** [comment]
> [2023-08-12 23:59:15.420][INF][Px1898][Txd18] load D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template [2023-08-12 23:59:15.436][ERR][Px1898][Txd18] Templ load failed, file not exists D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template\Mizuki@[Roguelike@GetDropCompleted.png](mailto:Roguelike@GetDropCompleted.png) [2023-08-12 23:59:15.436][TRC][Px1898][Txd18] asst::TemplResource::load | leave, 16 ms [2023-08-12 23:59:15.436][ERR][Px1898][Txd18] TaskData load failed, path: D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\tasks.json , templ dir: D:\a\MaaAssistantArknights\MaaAssistantArknights\x64\Debug\resource\template [2023-08-12 23:59:15.436][TRC][Px1898][Txd18] asst::ResourceLoader::load | leave, 6473 ms
> 
> 啊?

My bad, I was working on the roguelike all night and I've removed the wrong image. Sync the repo again, or copy the content of this 8b08e10aa35a64c61513f7efdf847fea8c927e1c in your PR.

**Comment by Constrat** [comment]
> Update tasks.json
> 
> image

Have you tested if `W.+` works? Because `.+` is used to detect at least more characters. If MAA detects only `W`, then this will not work.

**Comment by MistEO** [comment]
繁中应该少有英文的干员，现在来说应该是可以用的。但是我怕其他地方识别错了，出了个 W 开头的。比如 `银灰` 识别成了 `W银灰`，然后替换后出错了。

There should be very few operators with English names in Traditional Chinese, and this replacement should work now.
But I'm afraid that the wrong recognition in other places will start with a `W`. For example, `Silver Ash` be recognized as `WSilver Ash`, and then an error occurred after the replacement.

**Comment by Constrat** [comment]
> There should be very few operators with English names in Traditional Chinese, and this replacement should work now. But I'm afraid that the wrong recognition in other places will start with a `W`. For example, `Silver Ash` be recognized as `WSilver Ash`, and then an error occurred after the replacement.

True... Having `W.*` is almost a bypass, as soon as something is detected with a starting `W` everything breaks

**Comment by Constrat** [comment]
If more english names will appear (hopefully not) a solution (ugly but could work) would be to incapsulate everything with `.*`
`.*银灰.*` but I think this is a desperate measure as this could break even more stuff.

**Comment by Constrat** [comment]
@MistEO Well... It was already implemented `^w$`, no need for it on the EN.

> 是說這個 PR 感覺可以關起來了...嗎 (? 因為在 #5993 這個 PR 裡已經有補上針對 W 的識別了
> 
> 不知道幾位大佬們覺得如何?
> 
> Do you think we could possibly close this Pull Request...? 🤔 Cause #5993 has already added new OCR Replace rules for W.
> 
> ```
> [
>                 "^w$",
>                 "W"
> ],
> ```

We can definitely close this considering this exact was fixed with #5933.
If other issues arise re-opening this "is free" 😄

**Comment by Constrat** [comment]
> I think add `^w$` to EN might be a good idea! Cause #5993 is for twxy, I not sure if EN have same problem or not (?
 Yeah same issue. I'll just add it to the official is @MistEO is ok with it (I'm thinking this could be a problem for all overseas clients)

**Pull request closed without merging**
