### PR TITLE
Update for YostarKR (roguelike & credit store)

### PR DESCRIPTION
**Pull request by 178619**
Probably the last pull request from me for some time (again)

Fixed minor OCR errors
#4930: added `CreditShop-ProductName` - `ocrReplace`

### CODE REVIEW

**Comment by MistEO** [comment]
maybe try

```json
	"ocrReplace": [
            [
                " ",
                ""
            ],
            [
                " ",
                ""
            ]
	]
```

**Comment by MistEO** [comment]
Oh no, I was wrong, just pretend I didn't say it. XD

**Comment by MistEO** [comment]
No problem! If you join us, you can submit code more conveniently, and we don't have any contribution or other restrictions.

**Comment by 178619** [comment]
I will join if that is the case. Thanks for the invitation!

**Pull request merged**
