### PR TITLE
fix: YostarJP ocr sami/mizuki

### PR DESCRIPTION
**Pull request by teiyanesu**
fix [#10313](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10313) 
按照新手教學來到這邊的,不太確定是不是要上傳?
跑了一晚上沒卡住應該是好了

已經oxipng優化過 `oxipng -o 4 --strip safe --alpha *.png`

全部都是自己摸索不知道是否正確望海涵
感謝

### CODE REVIEW

**Comment by Constrat** [comment]
Were the templates changed? Also the second template seems more blurry now, don't know how that can fix it.

**Comment by Manicsteiner** [comment]
```
[2024-08-22 18:27:56.436][TRC][Px4848][Tx1dd0] match_templ | Mizuki@Roguelike@StageEncounterLeaveConfirm.png score: 0.73988 rect: [ 1114, 409, 161, 56 ] roi: [ 1063, 0, 217, 700 ]
[2024-08-22 18:27:56.634][TRC][Px4848][Tx1dd0] asst::WordOcr [{ ,動を操り返した後、機械は: [ 3, 101, 238, 18 ], score: 0.983084 }, { 上うてすべての昼品: [ 49, 127, 186, 13 ], score: 0.822613 }] by OCR Pipeline , cost 174 ms
```
看起来似乎更糟糕了

**Comment by teiyanesu** [comment]
emmm,有爬文是有發現好像判定類的都會因使用者而異,得要手動改

**Comment by Constrat** [comment]
It might be more about resolution, then DPI. Since MAA downscales everything to 720. If the emulator runs at 1080, the template 1080 -> 720 might be different from the original template if taken from 720 directly. Try switching ti different resolutions, 720, 900, 1080 etc.

**Pull request closed without merging**
