### PR TITLE
fix: Modified operators regex for Auto Squad and role button

### PR DESCRIPTION
**Pull request by Constrat**
From  #5235 
Most of the operators get detected, i'm noticing some issues with Ch'En the Holungday and Hibiscus the Purifier that don't get detected. Asst.log doesn't show anything of those two operators. Sometimes both Ch'en Alter and Hibiscus get detected, sometimes not. ~~I think I'm noticing a pattern: if they are on the top row of operators they detected, otherwise they don't.~~
Tried it again and it doesn't pick up Hibiscus alter even if it's on the top row

In this screen I tried getting the bot to pick Bagpipe first and then Ch'En alter
Screenshot_2023 06 25_14 45 13 534

14:44:56.994 timestamp for Ch'en undetected (BattleQuickFor
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11859750/asst.log)
mation-OperNameFlag.png gets detected correctly)

Question:
in the EN tasks.json with some opeators I can use this syntax
            [
                ".*arl the Radiant Knight",
                "Nearl the Radiant Knight"
            ],
            [
                "Nearl the Radiant Knight",
                "耀骑士临光"
            ],

and it works as expected replacing the Word at every step.
But sometimes it doesn't work like here:
            [
                ".*cter the Unchained",
                "归溟幽灵鲨"
            ],
            [
                "Specter the Unchained",
                "归溟幽灵鲨"
            ],
I have to manually place the chinese characters on the first call of the operator.
Having the second ocrReplace is now useless because they always pass on the first one. Is this intended or am I missing something?

### CODE REVIEW

**Comment by MistEO** [comment]
In the operator identification function, we use the role icon as the detection object. But in the formation function, we use the corner icon as the detection object, which is not good, because when the name is very long, the corner will be blocked and cannot be detected. We may change it to the same way as operator identification in the future.

**Comment by MistEO** [comment]
We can still merge this PR for now, as a temporary solution. Thanks for your contribution!

**Comment by Constrat** [comment]
No problem

> In the operator identification function, we use the role icon as the detection object. But in the formation function, we use the corner icon as the detection object, which is not good, because when the name is very long, the corner will be blocked and cannot be detected. We may change it to the same way as operator identification in the future.

But looking at the logs, the corner of the operator box gets identified correctly:
{ rect: [ 379, 603, 12, 20 ], score: 0.976320 }
The 379, 603 coordinate is the bottom row first box. But if you are telling me that the formation function is planned to go the same as the identificator I won't pry more. Thank you for the quick answer!

**Comment by MistEO** [comment]
> I have to manually place the chinese characters on the first call of the operator.
Having the second ocrReplace is now useless because they always pass on the first one. Is this intended or am I missing something?

Oh I didn't notice that, 

- Only the first is needed, the second is redundant. 

	```json
	            [
	                ".*cter the Unchained",
	                "归溟幽灵鲨"
	            ],
	            [
	                "Specter the Unchained",
	                "归溟幽灵鲨"
	            ],
	```

-  Can be merged into one. 

	```json
	            [
	                ".*arl the Radiant Knight",
	                "Nearl the Radiant Knight"
	            ],
	            [
	                "Nearl the Radiant Knight",
	                "耀骑士临光"
	            ],
	```
	to
	```json
	            [
	                ".*arl the Radiant Knight",
	                "耀骑士临光"
	            ],
	```

**Comment by Constrat** [comment]
But the thing is... In the first case with Nearl, it works correctly it double replaces first the full name and then in Chinese but with specter, when I tried it only replaces the first time, without replacing the full name to Chinese. It seemed a little strange that in some cases it worked and in others it didn't. With Nearl and all the other operators I prefer having the double replace because In case the new one doesn't work, the other one works as expected in all the other game modes.
ALSO... While letting MAA do 10-16 I noticed that with Nearl alter new skin, che it tries in fight to detect the name it misses the last T in radiant kighT so I'll have to edit that out

**Pull request merged**
