### PR TITLE
feat: 新增领取邮件功能

### PR DESCRIPTION
**Pull request by broken-paint**
First PR， ~~xjb水~~了领取邮件的task，不知道可不可行  

sto第一次整pull request如有错误或不完善的地方请大佬们多多指教orz

另外如何用vscode开发？

### CODE REVIEW

**Review by zzyyyl — CHANGES_REQUESTED** [review]
这样应该是不行的。按照你现在所写的，大概会变成领取任务奖励和邮件二选一？

可以像 `AwardBegin` `Award@xxx`，新建一个任务链然后加一些代码到 [AwardTask.cpp](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaCore/Task/Interface/AwardTask.cpp) 里

也许可以参考 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/1fbcf09ef45dc7508e55a552337fe15709839950 [MallTask.cpp](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaCore/Task/Interface/MallTask.cpp)

**Comment by zzyyyl** [comment]
vscode 写写 json 估计还行，调试 cpp 什么的还是用 VS 吧（

**Comment by Constrat** [comment]
Working on C, C++ and C# with VScode on bij projects is more hard than fun.
Also MAA has a .sln which is the solution for VS. It's easier to just install VS with C++ development and open the solution.

**Comment by broken-paint** [comment]
不懂底层实现，照着[MallTask.cpp](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/src/MaaCore/Task/Interface/MallTask.cpp)瞎整了下QAQ

**Review by zzyyyl — DISMISSED** [review]
改完记得自己先测测

**Comment by broken-paint** [comment]
改了，不知道逻辑还有没有错（如果没有 上面CloseTaskAward好像可以优化？ ~~但我估计还会有错~~
这样的话应该要改GUI？但咱不会（我太菜了qwq

**Comment by broken-paint** [comment]
> 改了，不知道逻辑还有没有错（如果没有 上面CloseTaskAward好像可以优化？ ~但我估计还会有错~ 
这样的话应该要改GUI？但咱不会（我太菜了qwq

现在还是不能运行

**Comment by zzyyyl** [comment]
GUI不用改的

应该还得识别领取完的白色返回？不然之后的任务可能会卡住

**Comment by broken-paint** [comment]
识别不出这几个png。。

**Comment by SherkeyXD** [comment]
gui 的逻辑改了吗

**Comment by broken-paint** [comment]
GUI没动，感觉加个选项合适点

**Comment by SherkeyXD** [comment]
> GUI没动，感觉加个选项合适点

加在领取日常奖励里面，然后默认不启用吧

**Comment by broken-paint** [comment]
大概能用了XD 
但是我不是很会搞GUI。。尽量~~瞎JB~~整整

**Comment by zzyyyl** [comment]
其实 GUI 不会整也没事，之后让 @SherkeyXD 他写：）

**Comment by broken-paint** [comment]
改了改GUI，现在应该还跑不了。（stostosto召唤大佬来看看哪里还要写orzorzorz

**Comment by broken-paint** [comment]
好像能用了o(*￣▽￣*)ブ
多语言需要翻译
还有哪里需要改进吗？

**Review by zzyyyl — CHANGES_REQUESTED** [review]
Mail
建议使用带小红点的邮件图标，可能匹配阈值不用设那么低
另外建议 `MailFinished` 改个名字，这个按钮比较有通用性，可以叫什么 `ReturnTo-White` 之类的（x

**Comment by Constrat** [comment]
If you haven't claimed anything, there's a dot. But if you go in the mail WIthout collecting anything, does the for remain?  As to check if there's really mail, without wasting time if there's any

**Review by zzyyyl — APPROVED** [review]

**Comment by broken-paint** [comment]
>If you haven't claimed anything, there's a dot. But if you go in the mail WIthout collecting anything, does the for remain? As to check if there's really mail, without wasting time if there's any

I've changed task.json. It will check if there is a dot and decide whether go in or not.
However, since the dot may appear after returning to home for a while, I am worried it might cause a mistake.

Is there a better solution?

**Review by SherkeyXD — APPROVED** [review]

**Comment by zzyyyl** [comment]
这 pr 历史怎么一坨（

**Comment by Constrat** [comment]
Squashing is definitely the better option

**Pull request merged**
