### PR TITLE
fix: encounter number in Mizuki IS

### PR DESCRIPTION
**Pull request by Constrat**
This was changed in #6102  4a6316c76a8db1e5ca101b14c53ec2ff429056d0 @Yumi0606 @Lancarus
This is the encounter for the 3rd ending. There should only be two options. Not three. In my case, MAA selected the "second" options out of 3 which resulted in choosing the 3rd ending which loses a lot of light.

### CODE REVIEW

**Comment by Yumi0606** [comment]
image

**Comment by Yumi0606** [comment]
From wiki.There is indeed a situation where the MAA chooses three endings and loses the light, which was originally intended to be modified in the previous update, but I have no time TwT.
Your modification seems to be wrong.Maybe it should be "Choose":3 and "option_num":3 ?

**Comment by Constrat** [comment]
> image

Now It makes sense. This update is still not live.

**Comment by Constrat** [comment]
> Your modification seems to be wrong.Maybe it should be "Choose":3 and "option_num":3 ?

image
As you can see in our version there's still only two options.

**Comment by Pitiedwzr** [comment]
> > Your modification seems to be wrong.Maybe it should be "Choose":3 and "option_num":3 ?
>
> As you can see in our version there's still only two options.
>
I think you need to clear any ending to unlock the second option 'Caerula', for my game there are three options.
MuMuPlayer_TqsgN6MKuw

**Comment by Constrat** [comment]
> > > Your modification seems to be wrong.Maybe it should be "Choose":3 and "option_num":3 ?
> > 
> > 
> > As you can see in our version there's still only two options.
> 
> I think you need to clear any ending to unlock the second option 'Caerula', for my game there are three options. MuMuPlayer_TqsgN6MKuw

Oh right, I forgot about that one. You need to get a clear to unlock the new "stuff"

**Comment by Constrat** [comment]
My bad everyone

**Comment by Constrat** [comment]
image
I got it.

**Pull request closed without merging**
