### PR TITLE
Update tasks.json (EN, #4978)

### PR DESCRIPTION
**Pull request by 178619**

### CODE REVIEW

**Comment by ABA2396** [comment]
Speaking of which, why are there two identical entries in the code block:
```
            [
                "Stainless™ Multifunctional Platform",
                "白铁™多功能平台"
            ],
            [
                "Stainless™ Multifunctional Platform",
                "白铁™多功能平台"
            ],
```
And it seems that the symbol '™' might not be recognized easily. How about replacing it with '.?' or '.*'?

Also, regarding the following entries:
```
            [
                "First-aid Kit",
                "急救包"
            ],
            [
                "Tide-Hunt Knight",
                "猎潮的骑士"
            ],
            [
                "8-Sided Dice",
                "8面骰子"
            ]
```
Would the dash '-' be correctly recognized?

**Comment by 178619** [comment]
>Speaking of which, why are there two identical entries in the code block: 

I think the Auto Update thing caused it. KR one had those, pretty sure JP one also has those duplicates.
>Would the dash '-' be correctly recognized?

I have no idea, can anyone who plays EN confirm this?

**Comment by Constrat** [comment]
Honestly, I don't think that was an issue because during yesterday testing the only problem was the recruit... But maybe I wasn't lucky enough to get any of the items you listed above, that have a `-`.

**Review by Constrat — APPROVED** [review]
Works great!
https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/cf1b8e2e-b8b9-4123-bfe1-ffd1eeb30165

**Pull request merged**
