### PR TITLE
feat: 外服生息演算支持 | Reclamatiom Algorithm global implementation

### PR DESCRIPTION
**Pull request by ABA2396**
@wallsman @Constrat @momomochi987 

外服的生息演算开了，我加回了对应服务器的任务入口，不过有些地方还是用到了 ocr 匹配，可以帮忙适配下吗？

The Reclamation Algorithm for the foreign server is up, and I've added the corresponding client task entry. However, in some places, OCR matching is still being used. Can you help adapt it?

外部サーバーのReclamation Algorithmが起動しており、対応するclientタスクのエントリを追加しました。ただし、一部の箇所ではOCRマッチングがまだ使用されています。お手伝いできますか？

### CODE REVIEW

**Comment by momomochi987** [comment]
啊啊生息演算
但我本身只有台服帳號，這部分暫時還幫不上忙 ( ´•̥̥̥ω•̥̥̥` )
等台服開生息演算的時候，我再來補 🙈

~~先來問問朋友有沒有其他服帳號可以借來看看~~

I only have a txwy account, and txwy doesn't have 'The Reclamation Algorithm' right now....
I'll update these tasks when it becomes available.  :(

**Comment by wallsman** [comment]
Helping is not a problem.
What should I do?

**Comment by Constrat** [comment]
I've changed the tools/overseas clients
Now it shows reclamation algorithm missing templates / text lines. I noticed someone already made a PR of missing images. Honestly I would prefer working only on this PR

**Comment by momomochi987** [comment]
```
  "Reclamation@TodoEnter": {
        "text": [
            "WITHIN",
            "沙",
            "中",
            "之",
            "火"
        ]
    },
    "Reclamation@EmptyInitUnits": {
        "text": [
            "请选择",
            "参加",
            "演算"
        ]
    },
    "Reclamation@ConfirmStart": {
        "text": [
            "演算",
            "开始"
        ]
    },
    "Reclamation@SkipAnnounce": {
        "text": [
            "跳过"
        ]
    },
    "Reclamation@SkipDailyReport": {
        "text": [
            "今日",
            "日报"
        ]
    },
    "Reclamation@ClickAnyZoneOcr": {
        "text": [
            "区",
            "Zone"
        ]
    },
    "Reclamation@StartActionEnter": {
        "text": [
            "开始行动",
            "决断"
        ]
    },
    "Reclamation@PrepareAction": {
        "text": [
            "行动准备"
        ]
    },
    "Reclamation@ExitLevelConfirm": {
        "text": [
            "确认",
            "离开"
        ]
    },
    "Reclamation@LevelComplete": {
        "text": [
            "结束",
            "MISSON",
            "RESULTS"
        ]
    },
    "Reclamation@GiveupAlgorithm": {
        "text": [
            "放",
            "弃"
        ]
    },
    "Reclamation@GiveupCrossdomainPageFlag": {
        "text": [
            "确认",
            "带走",
            "紧急",
            "撤退"
        ]
    },
    "Reclamation@GiveupClickEmergencyExit": {
        "text": [
            "紧急",
            "撤退"
        ]
    },
    "Reclamation@GiveupCheckRemainItems": {
        "text": [
            "查看",
            "物品"
        ]
    },
    "Reclamation@GiveupTakeNothing": {
        "text": [
            "确认",
            "撤退"
        ]
    },
    "Reclamation@AtCmdCenterFlag": {
        "text": [
            "COM",
            "MAND",
            "ENTER"
        ]
    },
    "Reclamation@EnterSmeltGoldPage": {
        "text": [
            "粗制",
            "赤金"
        ]
    },
    "Reclamation@EnterResearchLab": {
        "text": [
            "研",
            "究",
            "所"
        ]
    },
    "Reclamation@LabClickDetailView": {
        "text": [
            "详",
            "情",
            "视",
            "图"
        ]
    },
    "Reclamation@LabClickAssembleable": {
        "text": [
            "可",
            "组",
            "装"
        ]
    },
    "Reclamation@ManufactureIncrease": {
        "text": [
            "开",
            "始"
        ]
    },
    "Reclamation@ManufactureDecrease": {
        "text": [
            "材",
            "料",
            "不",
            "足"
        ]
    },
    "Reclamation@DoManufacture": {
        "text": [
            "开",
            "始"
        ]
    },
    "Reclamation@ManufactureInsufficientMaterial": {
        "text": [
            "材",
            "料",
            "不",
            "足"
        ]
    },
    "Reclamation@ManufactureSufficientMaterial": {
        "text": [
            "开",
            "始"
        ]
    },
    "Reclamation@Liaison": {
        "text": [
            "联络员"
        ]
    },
    "Reclamation@BuyWaterProcedure": {
        "text": [
            "Skip",
            "建材",
            "清水",
            "Skip"
        ]
    }
```

I think these are the tasks need to be translate, and add into EN and JP task.json

Hope it will helps (?

**Comment by Constrat** [comment]
They are correct, but what I meant is: understanding where they are on the screen.
Detecting images and adapting them is easy because even without translation you can just guess the image.
With the text it's harder, because unless I know the position in the CN server, it's easy to make mistakes adapting them. Because I could translate it, but it's not the correct text in the En for example.

**Comment by momomochi987** [comment]
https://www.youtube.com/watch?v=unQstFmpEnM

Maybe this JP introducing video could help you find where are the text (?

**Comment by wallsman** [comment]
> https://www.youtube.com/watch?v=unQstFmpEnM
> 
> Maybe this JP introducing video could help you find where are the text (?

This movie is use CN ver.

**Comment by Constrat** [comment]
> https://www.youtube.com/watch?v=unQstFmpEnM
> 
> Maybe this JP introducing video could help you find where are the text (?

Actually, it would be better if it was in ZH_CN

**Comment by wallsman** [comment]
> ```
>   "Reclamation@TodoEnter": {
>         "text": [
>             "WITHIN",
>             "沙",
>             "中",
>             "之",
>             "火"
>         ]
>     },
>     "Reclamation@EmptyInitUnits": {
>         "text": [
>             "请选择",
>             "参加",
>             "演算"
>         ]
>     },
>     "Reclamation@ConfirmStart": {
>         "text": [
>             "演算",
>             "开始"
>         ]
>     },
>     "Reclamation@SkipAnnounce": {
>         "text": [
>             "跳过"
>         ]
>     },
>     "Reclamation@SkipDailyReport": {
>         "text": [
>             "今日",
>             "日报"
>         ]
>     },
>     "Reclamation@ClickAnyZoneOcr": {
>         "text": [
>             "区",
>             "Zone"
>         ]
>     },
>     "Reclamation@StartActionEnter": {
>         "text": [
>             "开始行动",
>             "决断"
>         ]
>     },
>     "Reclamation@PrepareAction": {
>         "text": [
>             "行动准备"
>         ]
>     },
>     "Reclamation@ExitLevelConfirm": {
>         "text": [
>             "确认",
>             "离开"
>         ]
>     },
>     "Reclamation@LevelComplete": {
>         "text": [
>             "结束",
>             "MISSON",
>             "RESULTS"
>         ]
>     },
>     "Reclamation@GiveupAlgorithm": {
>         "text": [
>             "放",
>             "弃"
>         ]
>     },
>     "Reclamation@GiveupCrossdomainPageFlag": {
>         "text": [
>             "确认",
>             "带走",
>             "紧急",
>             "撤退"
>         ]
>     },
>     "Reclamation@GiveupClickEmergencyExit": {
>         "text": [
>             "紧急",
>             "撤退"
>         ]
>     },
>     "Reclamation@GiveupCheckRemainItems": {
>         "text": [
>             "查看",
>             "物品"
>         ]
>     },
>     "Reclamation@GiveupTakeNothing": {
>         "text": [
>             "确认",
>             "撤退"
>         ]
>     },
>     "Reclamation@AtCmdCenterFlag": {
>         "text": [
>             "COM",
>             "MAND",
>             "ENTER"
>         ]
>     },
>     "Reclamation@EnterSmeltGoldPage": {
>         "text": [
>             "粗制",
>             "赤金"
>         ]
>     },
>     "Reclamation@EnterResearchLab": {
>         "text": [
>             "研",
>             "究",
>             "所"
>         ]
>     },
>     "Reclamation@LabClickDetailView": {
>         "text": [
>             "详",
>             "情",
>             "视",
>             "图"
>         ]
>     },
>     "Reclamation@LabClickAssembleable": {
>         "text": [
>             "可",
>             "组",
>             "装"
>         ]
>     },
>     "Reclamation@ManufactureIncrease": {
>         "text": [
>             "开",
>             "始"
>         ]
>     },
>     "Reclamation@ManufactureDecrease": {
>         "text": [
>             "材",
>             "料",
>             "不",
>             "足"
>         ]
>     },
>     "Reclamation@DoManufacture": {
>         "text": [
>             "开",
>             "始"
>         ]
>     },
>     "Reclamation@ManufactureInsufficientMaterial": {
>         "text": [
>             "材",
>             "料",
>             "不",
>             "足"
>         ]
>     },
>     "Reclamation@ManufactureSufficientMaterial": {
>         "text": [
>             "开",
>             "始"
>         ]
>     },
>     "Reclamation@Liaison": {
>         "text": [
>             "联络员"
>         ]
>     },
>     "Reclamation@BuyWaterProcedure": {
>         "text": [
>             "Skip",
>             "建材",
>             "清水",
>             "Skip"
>         ]
>     }
> ```
> 
> I think these are the tasks need to be translate, and add into EN and JP task.json
> 
> Hope it will helps (?

It would be helpful if you could give us a screenshot or something of the relevant part of the Chinese version here, so we can be sure.

**Comment by momomochi987** [comment]
> It would be helpful if you could give us a screenshot or something of the relevant part of the Chinese version here, so we can be sure.

https://b23.tv/8ckmTKl

Try this (?

**Comment by Constrat** [comment]
@wallsman Unfortunately the Reclamation Algorithm is no more available on the CN so this is gonna be rough.

**Comment by Constrat** [comment]
> > It would be helpful if you could give us a screenshot or something of the relevant part of the Chinese version here, so we can be sure.
> 
> https://b23.tv/8ckmTKl
> 
> Try this (?

This looks promising!

**Comment by Constrat** [comment]
Ok, more templates that don't need adaptation incoming.

**Comment by momomochi987** [comment]
https://www.bilibili.com/video/BV1wd4y1H7jM

I think this video will be more useful.
It contains more content than the previous one.

**Comment by Constrat** [comment]
It's the full showcase! That's perfect, it should go in every single screen of the entire mode. That'll defintely help! tyvm

**Comment by Constrat** [comment]
👀

**Comment by ABA2396** [comment]
```
        public bool AsstAppendReclamation()
        {
            AsstTaskId id = AsstAppendTaskWithEncoding("ReclamationAlgorithm");
            _latestTaskId[TaskType.Recruit] = id;
            return id != 0;
        }
```
@MistEO  这里的[TaskType.Recruit]没问题吗？

**Comment by MistEO** [comment]
> ```
>         public bool AsstAppendReclamation()
>         {
>             AsstTaskId id = AsstAppendTaskWithEncoding("ReclamationAlgorithm");
>             _latestTaskId[TaskType.Recruit] = id;
>             return id != 0;
>         }
> ```
> @MistEO  这里的[TaskType.Recruit]没问题吗？

写错了吧，改改（

**Comment by Constrat** [comment]
I think this has to do with hereditary task problems? Like it happened with the Episode story navigation algorithm

**Comment by Constrat** [comment]
Also `Reclamation@ConfirmStart.png` is never used
image

NEVERMIND I-M DUMB, SORRY. I forgot that I had to reboot MAA to have the images reload.

**Comment by Constrat** [comment]
### EN Progress:
All images have been adapted. 
Texts to do:
- Reclamation@TodoEnter: WITHIN, 沙, 中, 之, 火
- Reclamation@LevelComplete: 结束, MISSON, RESULTS
- Reclamation@GiveupCrossdomainPageFlag: 确认, 带走, 紧急, 撤退
- Reclamation@GiveupClickEmergencyExit: 紧急, 撤退
- Reclamation@GiveupCheckRemainItems: 查看, 物品
- Reclamation@GiveupTakeNothing: 确认, 撤退
- Reclamation@EnterSmeltGoldPage: 粗制, 赤金
- Reclamation@EnterResearchLab: 研, 究, 所
- Reclamation@LabClickDetailView: 详, 情, 视, 图
- Reclamation@LabClickAssembleable: 可, 组, 装
- Reclamation@ManufactureIncrease: 开, 始
- Reclamation@ManufactureDecrease: 材, 料, 不, 足
- Reclamation@DoManufacture: 开, 始
- Reclamation@ManufactureInsufficientMaterial: 材, 料, 不, 足
- Reclamation@ManufactureSufficientMaterial: 开, 始
- Reclamation@Liaison: 联络员
- Reclamation@BuyWaterProcedure: Skip, 建材, 清水, Skip

Some of these don't need adaptation. Working on them right now...

**Comment by Constrat** [comment]
I'm not understanding why it's trying to create full builds for every single client every time a change is made, even to a .json. That doesn't make sense.

**Comment by Constrat** [comment]
I've tried a bit more with this but I'm still having issues: 
image
Whenever it reaches this, it searches for "Start". I've gave "Start" in the EN json 
```
    "Reclamation@StartActionEnter": {
        "text": [
            "Start"
        ]
    },
```
But it's not working. The log loops this:
```
[2023-09-08 18:10:11.302][INF][Px32b0][Tx40d0] {"class":"asst::ProcessTask","details":{"cur_retry":3,"retry_times":20,"to_be_recognized":["StartActionEnter@Reclamation@StartActionEnter"]},"first":["StartActionEnter@Reclamation@StartActionEnter"],"pre_task":"","subtask":"ProcessTask","taskchain":"ReclamationAlgorithm","taskid":1}
[2023-09-08 18:10:11.532][INF][Px32b0][Tx40d0] Call ` C:\Program Files\BlueStacks_nxt\.\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 230 ms , stdout size: 1324381 , socket size: 0
[2023-09-08 18:10:11.551][TRC][Px32b0][Tx40d0] asst::PipelineAnalyzer::analyze StartActionEnter@Reclamation@StartActionEnter
[2023-09-08 18:10:11.588][TRC][Px32b0][Tx40d0] asst::WordOcr [{ Act D1: [ 78, 69, 64, 21 ], score: 0.865032 }, { Start: [ 174, 68, 48, 25 ], score: 0.998415 }] by OCR Pipeline , cost 35 ms
[2023-09-08 18:10:11.588][TRC][Px32b0][Tx40d0] Proced []
[2023-09-08 18:10:11.588][TRC][Px32b0][Tx40d0] asst::ProcessTask::_run | leave, 285 ms
[2023-09-08 18:10:11.588][TRC][Px32b0][Tx40d0] ready to sleep 500
[2023-09-08 18:10:12.089][TRC][Px32b0][Tx40d0] end of sleep 500
[2023-09-08 18:10:12.089][TRC][Px32b0][Tx40d0] asst::ProcessTask::_run | enter
```
It's similar to what I've described before.

**Comment by ABA2396** [comment]
> I've added "Start" directly in the main tasks.json, this way, it works. Task: A@B@A, A@B might have some heavy issues trying to make them hereditary between jsons

cc @zzyyyl

**Comment by Constrat** [comment]
EDIT2: Something similar happens with
```
    "ClickedCorrectStageOrSwipe": {
        "action": "DoNothing",
        "baseTask": "StartButton1",
        "next": [
            "ClickedCorrectStage",
            "FullStageNavigation"
        ],
        "reduceOtherTimes": []
    },
```
^^^ This part of json needs to be copied in both of the clients (probably in ALL of the clients json because of the "different" baseTask)
Because the basetask is "StartButton1" and needs to be different for the clients:
EN: 
```
    "StartButton1": {
        "text": [
            "Start"
        ]
    },
```
CN:
```
    "StartButton1": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": [
            "开始行动"
        ],
        "cache": false,
        "preDelay": 500,
        "postDelay": 1000,
        "roi": [
            1038,
            640,
            206,
            46
        ],
        "exceededNext": [
            "StageSNReturnFlag",
            "Stop"
        ],
        "reduceOtherTimes": [
            "(ClickCornerAfterPRTS+ClickCorner)*5"
        ],
        "next": [
            "StartButton2",
            "StartButton2Adverse",
            "UseMedicine",
            "UseStone",
            "NoStone",
            "OfflineConfirm",
            "AnnihilationConfirm",
            "StartButton1TryAgain"
        ]
    },
```

**Comment by Constrat** [comment]
With EN I'm pretty much finished. The only missing part is this: 
- Reclamation@GiveupCrossdomainPageFlag: 确认, 带走, 紧急, 撤退
- Reclamation@GiveupTakeNothing: 确认, 撤退
I honestly have no idea where to look for these, I have kind of an idea but I'm not sure. (For now at least they are not important)

**Comment by zzyyyl** [comment]
If task `B` has _base task_ `A`, then **to apply the changes to `A` to `B`**, you need to declare `"baseTask": "A"` again.
For task `B@A` (which implicitly has _template task_ `A`), you need to declare `"baseTask": "#none"`

Refer to https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/en-us/3.4-TASK_SCHEMA.md#multi-file-task

**Comment by WLLEGit** [comment]
> With EN I'm pretty much finished. The only missing part is this:
> 
> * Reclamation@GiveupCrossdomainPageFlag: 确认, 带走, 紧急, 撤退
> * Reclamation@GiveupTakeNothing: 确认, 撤退
>   I honestly have no idea where to look for these, I have kind of an idea but I'm not sure. (For now at least they are not important)

As far as I remember, if "Transregional Communication" device has been established in the base and user has supplies to take away, there will be additional pages popping up when click giveup button on start page. These two tasks are triggered under these circumstances.

**Comment by Constrat** [comment]
> As far as I remember, if "Transregional Communication" device has been established in the base and user has supplies to take away, there will be additional pages popping up when click giveup button on start page. These two tasks are triggered under these circumstances.

Yeah I noticed the screen went green and it asked me to "Check supplies" but I've already adapted that, I still have two more strings to understand, they might be in that menu, but without CN texts / layouts it's very hard, as the translation is off-limits considering it's trash, I'll have another look today.

**Comment by Constrat** [comment]
(No idea how was that a conflict... I'll run the tests just to make sure it didn't break anything)

**Comment by Constrat** [comment]
> If task `B` has _base task_ `A`, then **to apply the changes to `A` to `B`**, you need to declare `"baseTask": "A"` again.
> For task `B@A` (which implicitly has _template task_ `A`), you need to declare `"baseTask": "#none"`

So in the case that I have a template task `B@A` and a task `C@B@A` in the CN, if I copy `B@A` in the EN and only change the parameter `"text"`, it won't work, I also need to copy `C@B@A` in the EN and adding `"baseTask": "B@A"`.
I've just tested it and it seems to work. If this is not the intended way, I'm all ears : )

**Comment by Constrat** [comment]
> As far as I remember, if "Transregional Communication" device has been established in the base and user has supplies to take away, there will be additional pages popping up when click giveup button on start page. These two tasks are triggered under these circumstances.

Ok I found it, you need to leave from a different place to make them show up but it worked! Thank you for the insight
for reference for JP and KR it's this 
<details><summary>Open Image</summary>
<p>

image
</p>
</details> 

And this:
<details><summary>Open Image</summary>
<p>

image
</p>
</details>

**Comment by Constrat** [comment]
One final thing:
What all of these do?
<details><summary>Lab tasks</summary>
<p>

```
Reclamation@EnterSmeltGoldPage ['粗制', '赤金']
Reclamation@EnterResearchLab ['研', '究', '所']
Reclamation@LabClickDetailView ['详', '情', '视', '图']
Reclamation@LabClickAssembleable ['可', '组', '装']
Reclamation@ManufactureIncrease ['开', '始']
Reclamation@ManufactureDecrease ['材', '料', '不', '足']
Reclamation@DoManufacture ['开', '始']
Reclamation@ManufactureInsufficientMaterial ['材', '料', '不', '足']
Reclamation@ManufactureSufficientMaterial ['开', '始']
Reclamation@Liaison ['联络员']
Reclamation@BuyWaterProcedure ['Skip', '建材', '清水', 'Skip']
```
</p>
</details> 
Guessing from the name and the ROI they are the Crafting and Gold menus of the Base. MAA can do all of that? I haven't seen it go there once, so I was wondering if I was doing missing something / doing wrong.

**Comment by foxwhite25** [comment]
> One final thing: What all of these do?
> 
> Lab tasks
> ```
> Reclamation@EnterSmeltGoldPage ['粗制', '赤金']
> Reclamation@EnterResearchLab ['研', '究', '所']
> Reclamation@LabClickDetailView ['详', '情', '视', '图']
> Reclamation@LabClickAssembleable ['可', '组', '装']
> Reclamation@ManufactureIncrease ['开', '始']
> Reclamation@ManufactureDecrease ['材', '料', '不', '足']
> Reclamation@DoManufacture ['开', '始']
> Reclamation@ManufactureInsufficientMaterial ['材', '料', '不', '足']
> Reclamation@ManufactureSufficientMaterial ['开', '始']
> Reclamation@Liaison ['联络员']
> Reclamation@BuyWaterProcedure ['Skip', '建材', '清水', 'Skip']
> ```
> 
> Guessing from the name and the ROI they are the Crafting and Gold menus of the Base. MAA can do all of that? I haven't seen it go there once, so I was wondering if I was doing missing something / doing wrong.

It could be used in crude pure gold farming mode (`"mode": 1`), by default (`"mode": 0`) it farms XP points and exchange currency. Basically MAA would buy water from Liaison and than craft things to farm gold.

**Comment by WLLEGit** [comment]
> Guessing from the name and the ROI they are the Crafting and Gold menus of the Base. MAA can do all of that? I haven't seen it go there once, so I was wondering if I was doing missing something / doing wrong.
> 
> 
> 

Melting gold was implemented and worked fine on my computer then. The ReclamationAlgorithm activity is nearly closed when it's done so we didn't add gui option. 
It could be invoked by changing the "mode" parameter. However it seems that this feature could not work now due to one of previous refactor commits, in which a whole function body is commented in ReclamationBattlePlugin.cpp for unknown reason

**Comment by Constrat** [comment]
[foxwhite25](https://github.com/foxwhite25)
> It could be used in crude pure gold farming mode (`"mode": 1`), by default (`"mode": 0`) it farms XP points and exchange currency. Basically MAA would buy water from Liaison and than craft things to farm gold.


[WLLEGit](https://github.com/WLLEGit)
> Melting gold was implemented and worked fine on my computer then. It's functionality is repeating the procedure of buying water in the black market(need to do some quests for unlock), melting gold in lab and exit. The ReclamationAlgorithm activity is nearly closed when it's done so we didn't add gui option.
> It could be invoked by changing the "mode" parameter. However it seems that this feature could not work now due to one of previous refactor commits, in which a whole function body is commented in ReclamationBattlePlugin.cpp for unknown reason

Thank you both! I was wondering where the setting was to make use of those tasks, but they have been hidden. Now everything adds up.

**Pull request merged**
