### PR TITLE
fix: 修复生息演算任务中的若干问题

### LINKED ISSUE #10410: 生息演算中使用荧光棒刷点数时滑动后点击判定错误
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

在4本生息演算制造刷点数中，由于制造荧光棒点击区与下方导航栏“科技树”按钮点击区过于接近，而将点击判定到科技树上，进而导致流程错误并退出。该问题在我的设备上出现概率极高，但仍有小概率能点击到正常位置。

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16824477/asst.log)
[gui.log](https://github.com/user-attachments/files/16824478/gui.log)
[gui.json](https://github.com/user-attachments/files/16824479/gui.json)

### 配置信息

操作系统：Windows 11 家庭中文版 23H2
模拟器品牌：雷电模拟器 9.0.76.3
模拟器分辨率：1920*1080 dpi280 帧率120fps
GPU加速：开启，NVIDIA GefForce RTX4060 Laptop，关闭GPU加速该问题仍然存在

### 截图或录屏

https://github.com/user-attachments/assets/39d73aa7-5d7d-4f86-8cf7-7847b05d7ad5

### 还有别的吗？

自己尝试了雷电模拟器的多个版本，发现在某一版本提及雷电模拟器存在滑动轨迹问题，该问题在旧版雷电模拟器中出现的尤其明显，在最新版雷电模拟器中出现概率略有下降，但仍然存在。

### LINKED ISSUE #10435: 生息演算相关
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

生息演算进程较上一版本感觉更像上上版本未修改的模样（生息演算闪退情况和停滞情况（指修改完高级设置后仍会停滞在同一界面）较为严重）

### Version

资源版本：泰拉饭24.09.02
界面版本：v5.6.0-beta.2
核心版本：v5.6.0-beta.2

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/16842757/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/16842758/asst.log)
在2024.9.3 10:10之后
[gui.json](https://github.com/user-attachments/files/16842760/gui.json)
[gui.new.json](https://github.com/user-attachments/files/16842761/gui.new.json)

### 配置信息

Windows11 MuMu模拟器12

### 截图或录屏

_No response_

### 还有别的吗？

_No response_

### LINKED ISSUE #10463: 开启截图增强后生息验算偶发报错
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

开启截图增强后  生息验算-通过开局刷点数  第一幕开始时 偶发报错
（已测试关闭截图增强挂机半小时无报错）
（报错位于视频02：00-02：15处）

### Version

Resource Version: 泰拉饭24.09.02
UI Version: v5.6.0-beta.2
Core Version: v5.6.0-beta.2

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16870683/gui.log)
[asst.log](https://github.com/user-attachments/files/16870685/asst.log)
[gui.json](https://github.com/user-attachments/files/16870686/gui.json)

### 配置信息

MuMu 12 V4.0.3(3244) DX模式 4核4G 1920x1080(dpi 280) 60fps
开启 MuMu 截图增强模式 开启 GPU 加速推理
NVIDIA GeForce GTX 1080
驱动程序版本:	32.0.15.6081
DirectX 版本:	12 (FL 12.1)

### 截图或录屏

https://github.com/user-attachments/assets/8fd328ed-54d8-4fa0-b9ab-cbd2b7455a9f

### 还有别的吗？

_No response_

### LINKED ISSUE #10528: 生息任务出错
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

出错
自动肉鸽没有问题，自动生息演算每次报错

### Version

Resource Version: 泰拉饭
Resource Time: 2024/9/6 01:26:34
UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16917078/asst.log)
[gui.log](https://github.com/user-attachments/files/16917079/gui.log)
2024/9/7   16:13:13生息演算任务出错
[gui.json](https://github.com/user-attachments/files/16917097/gui.json)

### 配置信息

Windows 10 专业版
MuMu 12，已开启截图增强
1600×900（DPI 240）60帧
无GPU加速推理

### 截图或录屏

出错

### 还有别的吗？

无

### LINKED ISSUE #10535: [日服]生息演算开局不久就任务出错
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

生息演算开局不久就任务出错
1.已清空编队
2.删除存档后重新开局

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16918514/asst.log)
[gui.log](https://github.com/user-attachments/files/16918515/gui.log)
[gui.json](https://github.com/user-attachments/files/16918517/gui.json)

### 配置信息

WIN10，雷电模拟器v9.0.69，1600*900，dpi240

### 截图或录屏

圖片_2024-09-07_214553026
圖片_2024-09-07_215802271

### 还有别的吗？

不时会卡在这个画面

### LINKED ISSUE #10539: 生息演算荧光棒刷点数任务出错
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

运行生息演算，制造完成荧光棒，进入下一天后就出现任务出错了。

### Version

Resource Version: 泰拉饭
UI Version: v5.6.0
Core Version: v5.6.0
Resource Time: 2024/9/6 01:26:34
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/16918694/gui.log)
[asst.log](https://github.com/user-attachments/files/16918696/asst.log)
[gui.json](https://github.com/user-attachments/files/16918697/gui.json)

### 配置信息

Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.4780
mumu模拟器12
2560*1440 DPI 360 60帧
未开启截图增强
开启GPU加速推理 AMD RX 6600 XT

### 截图或录屏

https://github.com/user-attachments/assets/05837e62-97ec-4461-9230-2bcafd4b27dc

微信图片_20240907224203

### 还有别的吗？

_No response_

### LINKED ISSUE #10542: 生息演算当基地无产出时无法进入下一日
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

使用生息演算制造荧光棒刷点数时，如游戏内处于荒季导致基地无产出，无法自动点击进入下一日，卡在以下界面；
image
手动点击后脚本继续正常运行，如不处理脚本报错并终止。

基地有产出时不出现此问题。

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16919058/asst.log)
[gui.log](https://github.com/user-attachments/files/16919059/gui.log)
[gui.json](https://github.com/user-attachments/files/16919060/gui.json)

### 配置信息

MuMu模拟器12，模拟小米12S Pro，1920*1080 (DPI 280)，60帧
已开启截图增强
已开启加速推理，GPU型号RTX 3070

### 截图或录屏

_No response_

### 还有别的吗？

_No response_

### PR DESCRIPTION
**Pull request by Alan-Charred**
1. 54a84b6 fixes #10435；
2. 894aaa4 fixes #10463；
3. bd17166 补上确认地图视图已重置到原始位置的机制，之前的版本没生效；
4. 9d70833 修复我自己遇到的进入下一天后卡住的问题，尚未有其他人反馈过，大概是因为我的电脑很卡很慢；
5. bf55822 fixes #10410；
6. 4418bb1 调整在组装台界面的下滑距离和参数，设置成稳定下滑两排的距离；
7. 3956332, ed2ad48 fix #10528, fix #10535，在点击区块节点后，会判断是否出现了 <开始行动> 按钮，如果没有出现则再次点击；
8. 11fdc3d, befd3f3 是从主界面到生息演算主题界面的导航；
9. ec4f1b2：有用户反应进入战斗关卡前后卡住，#10522, https://github.com/MaaAssistantArknights/maa-website/discussions/136#discussioncomment-10526217 ，我目前未能定位到具体原因，先加个延迟增加一下容错；之后想跟 @zzyyyl 老师讨论下能不能给 sub 加默认 500 delay 后，再多收集点报错日志，再考虑进一步加强容错率；另外，https://github.com/MaaAssistantArknights/maa-website/discussions/136#discussioncomment-10526217 看起来像是由于没有清空战斗编队而导致的，在 54a84b6 后应当已被修复，可用户说编队没有干员，我感到困惑，已进行交流，等有了日志文件再分析；

... 省略若干关于国际服适配导航的 commit

10. 1dc55fd fixes #10539, fixes #10542

给大家添麻烦了（鞠躬认错

### CODE REVIEW

**Comment by Alan-Charred** [comment]
image
这是目前的 roi
我给上调到565试试看
image

**Review by status102 — APPROVED** [review]
好像没啥问题

**Review by ABA2396 — DISMISSED** [review]

**Comment by Alan-Charred** [comment]
导航目前没适配国际服。大佬们先帮我看看逻辑对不对吧。谢谢。

**Comment by Alan-Charred** [comment]
@MaaAssistantArknights/global-support-team 

Dear Maa global support team, in this repo I add navigation from the main menu to Reclamation Algorithm.
The Official and EN parts has been done, and I need your help for JP and KR global adaptation.

There are two places to fill in.
1. The template depicted as below should be provided and named "Tales@RA@Navigation-FromTodoList.png".
Template

2. The text below (the concrete text in foreground) should be filled in the `text` field of task "RA@Navigation-EnterCurrentTheme". I have put placeholders there for you.
Template (1)

If feeling doubt, please refer to [24a8523](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10464/commits/24a85234d1a0176b52fe82be7625505aa59b303c).

Thanks a lot for your help!


Kind regards,

**Comment by Manicsteiner** [comment]
Screenshot_1723015481
Screenshot_1725722571

**Comment by Manicsteiner** [comment]
"RA@Navigation-RecogniseTheme" may also need text replacement

**Comment by Alan-Charred** [comment]
> "RA@Navigation-RecogniseTheme" may also need text replacement

Thanks for reminding! I will fix that part ASAP.
Btw, the global adaptation for JP has been done. Thanks for help!

**Comment by Alan-Charred** [comment]
> "RA@Navigation-RecogniseTheme" may also need text replacement

And it has been done in [a3a5ad0](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10464/commits/a3a5ad081ca47e96055971ef3c51ba4da1a47faf) . It's a combination of existing text.

**Comment by HX3N** [comment]
Screenshot_2024 09 08_02 04 35 037
Screenshot_2024 09 08_02 04 56 771

`"RA@Navigation-EnterCurrentTheme"` text can be used `"생존", "연산"`

**Comment by Alan-Charred** [comment]
> Screenshot_2024 09 08_02 04 35 037 Screenshot_2024 09 08_02 04 56 771
> 
> `"RA@Navigation-EnterCurrentTheme"` text can be used `"생존", "연산"`

Thanks a lot! Global adaptation for KR has been done in 19e1886.

Cheers,

**Review by ABA2396 — APPROVED** [review]

**Review by HoshinoAyako — APPROVED** [review]

**Pull request merged**
