### PR TITLE
chore: YoStarKR update tasks (RoguelikeTraderShoppingOcr)

### PR DESCRIPTION
**Pull request by HX3N**
I deleted the squads and effects in ```RoguelikeTraderShoppingOcr``` using Resource Updater(#8493)
About 60 items have been deleted

added some ocrReplace

### CODE REVIEW

**Comment by HX3N** [comment]
Is it right not to PR until the Resource Update is changed?
YoStarJP's squad and effect, which were deleted as #8522, have been re-created by Auto Resource Update, which just ran

**Comment by Constrat** [comment]
I still haven't updated the resource updater itself. Keep it as a PR for the time being.

**Comment by HX3N** [comment]
```
[2024-03-09 02:35:14.429][TRC][Pxcaf4][Tx5510] asst::WordOcr [{ 혼란의상징: [ 0, 0, 280, 55 ], score: 0.999434 }] by OCR Rec , cost 25 ms
[2024-03-09 02:35:14.429][TRC][Pxcaf4][Tx5510] Proceed [{ 混乱的表象: [ 500, 453, 280, 55 ], score: 0.999434 }]
```


```
[2024-03-09 02:39:29.176][TRC][Pxcaf4][Tx5510] asst::WordOcr [{ 우뚝 솟은 은빛 서리: [ 0, 0, 473, 55 ], score: 0.896238 }] by OCR Rec , cost 27 ms
[2024-03-09 02:39:29.177][TRC][Pxcaf4][Tx5510] Proceed [{ 우뚝 솟은 은빛 서리: [ 404, 453, 473, 55 ], score: 0.896238 }]
```

I'm not sure why, but unlike "混乱的表象" and other stages, only "巍峨银凇" is recognized including spaces. (巍峨银凇 =우뚝 솟은 은빛 서리)
So I added the following ocrReplace on ```BattleStageName```

```
            [
                " ",
                ""
            ],
```

**Comment by Constrat** [comment]
If you remove all spaces from the encounters, you HAVE TO add the wildcard " " => "", otherwise in the unexpected case it gives a space, it won't get recognised

**Comment by HX3N** [comment]
> If you remove all spaces from the encounters, you HAVE TO add the wildcard " " => "", otherwise in the unexpected case it gives a space, it won't get recognised

I thought it was there, but turns out it wasn't. 😂

**Comment by Constrat** [comment]
@HX3N Check 6b5f836e2208655ce7954d11e98a1a16f52c6178 out.
To try it, delete all items in the encounter.
This version also supports the reduced trader items. The total number of relics should amount to 516. 
Unfortunately to run it correctly, you have to first run only the Phantom IS, then Phanton + Mizuki and finally Sami.
This is because if you run the 3 together the first time with a CLEAR `RoguelikeTraderShoppingOcr`, it will not pickup any duplicates, and you would reach almost ~1200 replaces... Not ideal.

This is a lot of work, but should help performance. I wish there was an easy way to "transfer" the wanted regex over, and remove the useless items, but it seems it wants to reorder everything and git does a horrible job sorting everything.
(If the regex for the trader wasn't a lot to start with it should be easier)

**Comment by HX3N** [comment]
Items obtained through random encounters, such as collectibles and effects like ```目标生命```,```源石锭```,```希望``` (etc..), that are not sold in stores have been removed.

The resource updater seems to be working fine.

**Comment by Constrat** [comment]
> Items obtained through random encounters, such as collectibles and effects like `目标生命`,`源石锭`,`希望` (etc..), that are not sold in stores have been removed.
> 
> The resource updater seems to be working fine.

There shouldn't be that many. In my test I reached 516 items. The lowest number should be 514 (this was calculated from the 3 shopping.json and removing the duplicates)

**Comment by HX3N** [comment]
>There shouldn't be that many. In my test I reached 516 items. The lowest number should be 514 (this was calculated from the 3 shopping.json and removing the duplicates)

I managed to reduce it with regular expressions, and now there are 517 items.
It seems to have been handled well.

**Comment by Constrat** [comment]
> Additionally, upon checking once, it seems that when updating `StageEncounterOcr` with Resource Updater, spaces are removed well :D

Yep, added that for KR only

**Comment by HX3N** [comment]
> ```
> [2024-03-09 02:35:14.429][TRC][Pxcaf4][Tx5510] asst::WordOcr [{ 혼란의상징: [ 0, 0, 280, 55 ], score: 0.999434 }] by OCR Rec , cost 25 ms
> [2024-03-09 02:35:14.429][TRC][Pxcaf4][Tx5510] Proceed [{ 混乱的表象: [ 500, 453, 280, 55 ], score: 0.999434 }]
> ```
> 
> ```
> [2024-03-09 02:39:29.176][TRC][Pxcaf4][Tx5510] asst::WordOcr [{ 우뚝 솟은 은빛 서리: [ 0, 0, 473, 55 ], score: 0.896238 }] by OCR Rec , cost 27 ms
> [2024-03-09 02:39:29.177][TRC][Pxcaf4][Tx5510] Proceed [{ 우뚝 솟은 은빛 서리: [ 404, 453, 473, 55 ], score: 0.896238 }]
> ```
> 
> I'm not sure why, but unlike "混乱的表象" and other stages, only "巍峨银凇" is recognized including spaces. (巍峨银凇 =우뚝 솟은 은빛 서리) So I added the following ocrReplace on `BattleStageName`
> 
> ```
>             [
>                 " ",
>                 ""
>             ],
> ```


The issue above has not been resolved.
I will submit a new PR after resolving the problem.

```
[2024-03-10 15:24:21.491][TRC][Px2dbc][Tx3384] asst::WordOcr [{ 우뚝 솟은 은빛 서리: [ 0, 0, 473, 55 ], score: 0.896238 }] by OCR Rec , cost 210 ms
[2024-03-10 15:24:21.492][TRC][Px2dbc][Tx3384] Proceed [{ 우뚝 솟은 은빛 서리: [ 404, 453, 473, 55 ], score: 0.896238 }]
```

**Pull request closed without merging**
