### PR TITLE
docs: YostarEN recommended resolution

### PR DESCRIPTION
**Pull request by Constrat**
Need help with the translations.

### CODE REVIEW

**Comment by MistEO** [comment]
What went wrong? Theoretically there is no difference between different resolutions.

**Comment by Constrat** [comment]
#5235

**Comment by momomochi987** [comment]
I suggest that changing the translation to the following text for a smoother flow in Chinese (?


For `docs/readme.md`

```
2. 修改模拟器分辨率为 `16:9` 比例，最低 `1280 * 720`，更高不限。强烈建议将国际服（美服）分辨率修改为 `1920 * 1080` ，避免因分辨率产生问题。
```

For `docs/zh-tw/readme.md`

```
2. 修改模擬器解析度為 `16:9` 比例，最低 `1280 * 720`，更高不限。強烈建議將國際服（美服）解析度修改為 `1920 * 1080` ，避免因解析度產生問題。
```

**Comment by Constrat** [comment]
> I suggest that changing the translation to the following text for a smoother flow in Chinese (?
> 
> For `docs/readme.md`
> 
> ```
> 2. 修改模拟器分辨率为 `16:9` 比例，最低 `1280 * 720`，更高不限。强烈建议将国际服（美服）分辨率修改为 `1920 * 1080` ，避免因分辨率产生问题。
> ```
> 
> For `docs/zh-tw/readme.md`
> 
> ```
> 2. 修改模擬器解析度為 `16:9` 比例，最低 `1280 * 720`，更高不限。強烈建議將國際服（美服）解析度修改為 `1920 * 1080` ，避免因解析度產生問題。
> ```

Will do! For the ZH I just copy pasted what the translator gave me, just to have an idea

**Comment by MistEO** [comment]
I think the format can be adjusted to

2. 修改模拟器分辨率为 `16:9` 比例，最低 `1280 * 720`，更高不限。  
    对于国际服（美服）玩家，由于界面布局问题，我们则建议您将分辨率修改为 `1920 * 1080`。

2. Change your emulator resolution to `1280 * 720` or higher with `16:9` aspect ratio.  
    For YostarEN, due to interface layout issues, we highly recommend that you change the resolution to `1920 * 1080`.

**Comment by Constrat** [comment]
> I think two lines would be better, like:
> 
> 2. 修改模拟器分辨率为 `16:9` 比例，最低 `1280 * 720`，更高不限。
>    对于国际服（美服）玩家，由于界面布局问题，我们则建议您将分辨率修改为 `1920 * 1080`。
> 3. Change your emulator resolution to `1280 * 720` or higher with `16:9` aspect ratio.
>    For YostarEN, due to interface layout issues, we highly recommend that you change the resolution to `1920 * 1080`.

I tried having them in a new line but the markdown preview wasn't following it.

**Comment by Constrat** [comment]
@momomochi987 I just need the `new` ZH_tw translation of what MistEO proposed.
Thank you 👍🏻

**Comment by momomochi987** [comment]
> @momomochi987 I just need the `new` ZH_tw translation of what MistEO proposed. Thank you 👍🏻

```
2. 修改模擬器解析度為 16:9 比例，最低 1280 * 720，更高不限。
對於國際服（美服）玩家，由於介面佈局問題，我們則建議您將解析度修改為 1920 * 1080。
```

(ﾉ>ω<)ﾉ

**Comment by MistEO** [comment]
For markdown, You can add two spaces at the end of the line, which means a new line. <br/> is also available, but this is an html syntax.

**Comment by Constrat** [comment]
> For markdown, You can add two spaces at the end of the line, which means a new line. is also available, but this is an html syntax.

Whatever you prefer :)

**Pull request merged**
