### PR TITLE
perf: 迁移部分模板图

### PR DESCRIPTION
**Pull request by status102**
迁移至
- #6686 
- #6687

### CODE REVIEW

**Comment by Lancarus** [comment]
任务名都是battle了,文件夹名也用battle吧?

**Comment by Constrat** [comment]
Is this really needed? the template names now become really long... As @Lancarus said they all have "Battle" in front, how about `Battle/QuickFormation` etc

**Comment by status102** [comment]
> Is this really needed? the template names now become really long... As @Lancarus said they all have "Battle" in front, how about `Battle/QuickFormation` etc

后面打算按照模块 (Fight、Infrast、Roguelike) 看看能不能拆分Task，如果拆不了，就不打算大批量改了。
全部改一遍template工作量太大，而且不能隐式声明了，没必要

**Comment by Constrat** [comment]
> 后面打算按照模块 (Fight、Infrast、Roguelike) 看看能不能拆分Task，如果拆不了，就不打算大批量改了。 全部改一遍template工作量太大，而且不能隐式声明了，没必要

Roguelike@ is definetely useful, as they take up a lot of space, but unfortunately there never has been a consistency in the naming scheme... We should change everything from zero, but that's a huge change and will take a lot of time.

**Comment by status102** [comment]
> Roguelike@ is definetely useful, as they take up a lot of space, but unfortunately there never has been a consistency in the naming scheme... We should change everything from zero, but that's a huge change and will take a lot of time.

这会是一个break changes，不过八字还没一撇，能不能拆还不好说

**Comment by status102** [comment]
> 感觉要是把 `@` 解释成文件夹的话，`Sami@Roguelike` 会是 `Sami/Roguelike`，但是实际上应该是 `Roguelike/Sami`（ 也许可以加个配置文件表示某个前缀对应某个文件夹？

直接解释@感觉会很乱

**Comment by status102** [comment]
迁移至
- #6686 
- #6687

**Pull request closed without merging**
