### PR TITLE
chore: 補充繁中服薩米肉鴿相關內容

### LINKED ISSUE #9428: 台服萨米肉鸽无法运行
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

会一直 主界面，肉鸽，主界面，肉鸽循环，不会报错但是什么都没干。

### Version

v5.3.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15913065/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/15913068/asst.bak.log)

没找到gui.log

### 截图

Screenshot 2024-06-20 at 23 45 16
Screenshot 2024-06-20 at 23 45 27
Screenshot 2024-06-20 at 23 47 39

Screenshot 2024-06-20 at 23 47 45
Screenshot 2024-06-20 at 23 47 58
Screenshot 2024-06-20 at 23 48 06

进了过后就会退出会主界面，然后重新开始

### 还有别的吗？

_No response_

### PR DESCRIPTION
**Pull request by momomochi987**
fix #9428 

接續 #9429 

把遺漏的部分補一補 & 改一些有遇到的 ocr 文字問題

### CODE REVIEW

**Comment by spreee163** [comment]
補充兩個我有發現ocr錯誤的關卡名
1.大遷徒
2.巍峨銀淋

**Comment by Constrat** [comment]
@momomochi987 do the encounters (events) and the items in the trader shopping work correctly?

**Comment by momomochi987** [comment]
> @momomochi987 do the encounters (events) and the items in the trader shopping work correctly?
> 
> I made some drastic changes a while back and only worked with YostarEN (and subsequentially the global) technically nothing should change for txwy (it should make things better since, it was a clean slate start, instead of having to correctly identify the duplicates etc)

Yes, they almost work correctly on my computer.

Sometimes, an "Error in level recognition" appears (ex:9453). I'm not sure if it's due to network fluctuations.

For 9465, I haven't chosen that strategy before, so I'm not sure what the problem is.

Right now, the problem I'm facing is like 8634, it gets stuck at choosing one of the two or more options.

**Comment by Constrat** [comment]
The choice is very probably caused by the fact that later updates of IS, will give more choices, and currently we don-t have multiple  IS versions, as we all follow the chinese even if we don't have that update yet)

**Pull request merged**
