### PR TITLE
chore: update python API

### PR DESCRIPTION
**Pull request by EvATive7**
The following interfaces are supported via this pr：
- set_connection_extras
- set_static_option

### CODE REVIEW

**Comment by aur3l14no** [comment]
Maybe add `get_image` as well?

```py
    def get_image(self, size) -> bytes | None:
        """
        获取上次截图

        : return: Image in bytes or None on failure
        """
        buffer = ctypes.create_string_buffer(b'\000' * (size - 1))
        if (size := Asst.__lib.AsstGetImage(self.__ptr, buffer, len(buffer))) \
            and size > 0:
            return bytes(buffer)
        else:
            return None

...

        Asst.__lib.AsstGetImage.restype = ctypes.c_uint64
        Asst.__lib.AsstGetImage.argtypes = (
            ctypes.c_void_p, ctypes.c_void_p, ctypes.c_uint64)
```

**Comment by aur3l14no** [comment]
Being picky here :D

1. The docstring of `set_static_option` are not consistent with params.
2. Maybe add return value to `set_connection_extras`?
3. Maybe add `get_image` as well?

```py
    def get_image(self, size) -> bytes | None:
        """
        获取上次截图
        :params:
            ``size``:  图像字节数, 如 1280*720*3

        : return: 成功时图像的字节; 失败时 None
        """
        buffer_type = ctypes.c_byte * size
        buffer = buffer_type()
        buffer.value = b'\000' * size
        if (got := Asst.__lib.AsstGetImage(self.__ptr, buffer, size)) \
            and got > 0:
            return bytes(buffer)
        else:
            return None

// ...

        Asst.__lib.AsstGetImage.restype = ctypes.c_uint64
        Asst.__lib.AsstGetImage.argtypes = (
            ctypes.c_void_p, ctypes.c_void_p, ctypes.c_uint64)
```

Example usage: `asst.get_image(1280*720*3)`

**Comment by EvATive7** [comment]
Thanks for your reply.

1. Got it. I will fix it.
2. MAACore won't return anything for calling `AsstSetConnectionExtras`. This is its prototype:
```cpp
void AsstSetConnectionExtras(const char* name, const char* extras)
```
3. Thanks for your code, I will add it.

**Review by SherkeyXD — APPROVED** [review]

**Comment by bigbanglwb** [comment]
can i use `set_connection_extras ` to enabel mumu extras ? which means enable `mumu 截图增强模式`. Is there any documents for this api ? Thank u

**Pull request merged**
