### PR TITLE
i18n: add favourite tip for i18n

### PR DESCRIPTION
**Pull request by Constrat**
Hopefully reduce duplicate wontfix issue count by reminding users to remove favourite operators before detection

### CODE REVIEW

**Comment by Constrat** [comment]
JP, KR, CN and TW are all machine translated (deepL and google translate)

**Comment by gui-ying233** [comment]
在 EN 中这个功能被称为 “mark”，在 CN 中被称为 “特别关注”；另，CN 的 “操作员” 的正确翻译应为 “干员”。

**Comment by Constrat** [comment]
@HX3N yes it's a community pr. No one has to reset / force push anything!

**Comment by Constrat** [comment]
TODO: tweak en i18n

**Comment by Manicsteiner** [comment]
```
「戦術要員」は、オペレーター識別の正確性に影響します。戦術要員のオペレーターの識別が誤っている場合は、自己判断してください。\n
```
↑ JP version

**Pull request merged**
