### PR TITLE
chore: update clang-format

### PR DESCRIPTION
**Pull request by MistEO**
效果参考：https://github.com/MaaXYZ/MaaFramework/pull/162

### CODE REVIEW

**Comment by Constrat** [comment]
The new formatting doesn't feel as good as the older one.
very ugly 
image

**Comment by status102** [comment]
> The new formatting doesn't feel as good as the older one. very ugly 

甚至注释也会被强制换行

before:
```
// ABC(123) 
```
after:
```
// ABC(12
// 3)
```
会有一些烦人，为了让他在同一行不得不考虑一下措辞

**Comment by MistEO** [comment]
> > The new formatting doesn't feel as good as the older one. very ugly
> 
> 甚至注释也会被强制换行
> 
> before:
> 
> ```
> // ABC(123) 
> ```
> 
> after:
> 
> ```
> // ABC(12
> // 3)
> ```
> 
> 会有一些烦人，为了让他在同一行不得不考虑一下措辞

之前的注释也是会强制换行的，只是之前的行限制比较长，超出屏幕很多了才会换，现在改短了一些。之前是 120，现在是 100，其实差不多（

**Comment by status102** [comment]
我这小屏幕就是刚好换（乐
然后昨天被那个换行烦死hhh

**Pull request merged**
