### PR TITLE
feat: 自动编队允许指定助战单位

### PR DESCRIPTION
**Pull request by Alan-Charred**

### CODE REVIEW

**Comment by Constrat** [comment]
@Alan-Charred Tried it since I was curios
(to make it work I forced Eyja Alter as a favourite operators meaning the OCR will fail (as I have Eyja Alter))

<details>
<summary>Log error</summary>

```py
[2024-11-05 13:06:30.130][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["UseSupportUnit-Enter"]},"first":["UseSupportUnit-Enter"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:30.145][TRC][Px4134][Tx3584] match_templ | UseSupportUnit-Enter.png score: 0.9511 rect: [ 1034, 323, 26, 30 ] roi: [ 1023, 314, 46, 50 ]
[2024-11-05 13:06:30.145][TRC][Px4134][Tx3584] asst::PipelineAnalyzer::analyze | MatchTemplate UseSupportUnit-Enter
[2024-11-05 13:06:30.145][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.951100},"task":"UseSupportUnit-Enter"},"first":["UseSupportUnit-Enter"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.145][TRC][Px4134][Tx3584] Click with scaled coordinates (1048, 341) 1.5
[2024-11-05 13:06:30.145][TRC][Px4134][Tx3584] minitouch click: (1572, 511)
[2024-11-05 13:06:30.246][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.951100},"task":"UseSupportUnit-Enter"},"first":["UseSupportUnit-Enter"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.246][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:30.747][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:30.747][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["UseSupportUnit-Enter@NextAfterLoadingText","UseSupportUnit-InSupportList"]},"first":["UseSupportUnit-Enter"],"pre_task":"UseSupportUnit-Enter","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:30.822][TRC][Px4134][Tx3584] asst::WordOcr [{ nc: [ 3, 17, 12, 9 ], score: 0.581624 }, { AnitaMaxWynn: [ 31, 79, 142, 23 ], score: 0.990539 }] by OCR Pipeline , cost 63 ms
[2024-11-05 13:06:30.828][TRC][Px4134][Tx3584] match_templ | UseSupportUnit-Refresh score: 0.902784 rect: [ 1106, 26, 32, 27 ] roi: [ 1096, 12, 61, 52 ]
[2024-11-05 13:06:30.828][TRC][Px4134][Tx3584] asst::PipelineAnalyzer::analyze | MatchTemplate UseSupportUnit-InSupportList
[2024-11-05 13:06:30.829][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.902784},"task":"UseSupportUnit-InSupportList"},"first":["UseSupportUnit-Enter"],"pre_task":"UseSupportUnit-Enter","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.829][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.902784},"task":"UseSupportUnit-InSupportList"},"first":["UseSupportUnit-Enter"],"pre_task":"UseSupportUnit-Enter","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.829][TRC][Px4134][Tx3584] asst::ProcessTask::run | leave, 699 ms
[2024-11-05 13:06:30.829][TRC][Px4134][Tx3584] asst::UseSupportUnitTaskPlugin::try_add_support_unit_for_role | enter
[2024-11-05 13:06:30.829][TRC][Px4134][Tx3584] asst::ProcessTask::run | enter
[2024-11-05 13:06:30.829][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:30.829][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":1,"max_times":2147483647,"result":null,"task":"UseSupportUnit-Role"},"first":["Medic@UseSupportUnit-Role"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.829][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"JustReturn","exec_times":1,"max_times":2147483647,"result":null,"task":"UseSupportUnit-Role"},"first":["Medic@UseSupportUnit-Role"],"pre_task":"","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:30.829][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:31.330][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:31.330][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-RoleSelected","Medic@UseSupportUnit-SelectRole"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-Role","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:31.356][TRC][Px4134][Tx3584] match_templ | Medic@UseSupportUnit-SelectRole.png score: 0.994849 rect: [ 20, 473, 73, 76 ] roi: [ 20, 93, 73, 608 ]
[2024-11-05 13:06:31.356][TRC][Px4134][Tx3584] asst::PipelineAnalyzer::analyze | MatchTemplate Medic@UseSupportUnit-SelectRole
[2024-11-05 13:06:31.356][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.994849},"task":"UseSupportUnit-SelectRole"},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-Role","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:31.356][TRC][Px4134][Tx3584] Click with scaled coordinates (68, 518) 1.5
[2024-11-05 13:06:31.356][TRC][Px4134][Tx3584] minitouch click: (102, 777)
[2024-11-05 13:06:31.457][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"result":{"score":0.994849},"task":"UseSupportUnit-SelectRole"},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-Role","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:31.457][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:31.958][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:31.958][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:32.015][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 43 ms
[2024-11-05 13:06:32.015][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":1,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:32.015][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:32.516][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:32.527][INF][Px4134][Tx3584] Assistant::append_callback | ConnectionInfo {"details":{"avg":11,"max":13,"min":10},"uuid":"accfc4f5c7755601","what":"ScreencapCost"}
[2024-11-05 13:06:32.563][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 34 ms
[2024-11-05 13:06:32.564][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":2,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:32.565][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:33.065][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:33.116][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 37 ms
[2024-11-05 13:06:33.116][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":3,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:33.116][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:33.616][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:33.663][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 33 ms
[2024-11-05 13:06:33.663][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":4,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:33.663][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:34.164][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:34.212][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 36 ms
[2024-11-05 13:06:34.213][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":5,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:34.213][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:34.714][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:34.761][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 33 ms
[2024-11-05 13:06:34.761][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":6,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:34.761][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:35.262][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:35.308][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 34 ms
[2024-11-05 13:06:35.308][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":7,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:35.308][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:35.810][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:35.854][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 31 ms
[2024-11-05 13:06:35.854][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":8,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:35.854][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:36.355][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:36.404][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 36 ms
[2024-11-05 13:06:36.405][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":9,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:36.405][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:36.906][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:36.946][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 26 ms
[2024-11-05 13:06:36.946][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":10,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:36.946][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:37.447][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:37.488][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 27 ms
[2024-11-05 13:06:37.488][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":11,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:37.488][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:37.988][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:38.000][INF][Px4134][Tx3584] Assistant::append_callback | ConnectionInfo {"details":{"avg":11,"max":12,"min":10},"uuid":"accfc4f5c7755601","what":"ScreencapCost"}
[2024-11-05 13:06:38.028][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 26 ms
[2024-11-05 13:06:38.028][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":12,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:38.028][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:38.529][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:38.569][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 26 ms
[2024-11-05 13:06:38.569][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":13,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:38.569][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:39.070][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:39.109][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 26 ms
[2024-11-05 13:06:39.109][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":14,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:39.109][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:39.611][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:39.662][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 37 ms
[2024-11-05 13:06:39.662][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":15,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:39.662][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:40.162][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:40.208][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 32 ms
[2024-11-05 13:06:40.208][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":16,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:40.208][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:40.710][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:40.749][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 27 ms
[2024-11-05 13:06:40.749][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":17,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:40.749][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:41.250][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:41.286][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 24 ms
[2024-11-05 13:06:41.286][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":18,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:41.286][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:41.788][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:41.832][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 30 ms
[2024-11-05 13:06:41.832][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":19,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:41.832][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:42.333][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:42.375][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 28 ms
[2024-11-05 13:06:42.375][INF][Px4134][Tx3584] {"class":"asst::ProcessTask","details":{"cur_retry":20,"retry_times":20,"to_be_recognized":["Medic@UseSupportUnit-Role@NextAfterLoadingText"]},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0}
[2024-11-05 13:06:42.375][TRC][Px4134][Tx3584] ready to sleep 500
[2024-11-05 13:06:42.876][TRC][Px4134][Tx3584] end of sleep 500
[2024-11-05 13:06:42.914][TRC][Px4134][Tx3584] asst::WordOcr [{ : [ 0, 0, 427, 115 ], score: 0.000000 }] by OCR Pipeline , cost 27 ms
[2024-11-05 13:06:42.915][INF][Px4134][Tx3584] Assistant::append_callback | SubTaskError {"class":"asst::ProcessTask","details":{},"first":["Medic@UseSupportUnit-Role"],"pre_task":"Medic@UseSupportUnit-SelectRole","subtask":"ProcessTask","taskchain":"Copilot","taskid":0,"uuid":"accfc4f5c7755601"}
[2024-11-05 13:06:42.915][TRC][Px4134][Tx3584] asst::ProcessTask::run | leave, 12085 ms
```


</details>

**Comment by Constrat** [comment]
[support.log](https://github.com/user-attachments/files/17632325/support.log)
Here's the full log.

I think the weird section is where Eyja is ocred correctly but as she's not in the friend list but only as recommended it correctly refreshes the page, but that is done only once. Without trying again.

**Review by status102 — APPROVED** [review]
中间PR，等后续进一步重构

**Comment by Constrat** [comment]
I see :)

**Comment by Alan-Charred** [comment]
> @Alan-Charred Tried it since I was curios (to make it work I forced Eyja Alter as a favourite operators meaning the OCR will fail (as I have Eyja Alter))
> 
> Here a subtaskerror happens and it waits quite a lot, but nothing important as then it continues and it correctly selectes the medic section. It correctly OCRs the names, E2 rank is good enough with the 0.7 threshold (lowest score is .77 highest is .81)
> 
> Log error

Thanks for testing!
Actually this PR is just for official/zh_cn-only for now, since it depends on the new support unit-selection menu, where you can select the skill after the operator -- even if OCR succeeds to work on EN side, something will get stuck after clicking the chosen support unit... since you cannot choose the skill...
And so far MAA do not have a database of skill icon so I can't tell the skill from the icon directly... otherwise I should add support for global players.

Whatever, I am so curious about this OCR issue, let me test it myself and I will come back to you later.

**Comment by Alan-Charred** [comment]
> @Alan-Charred Tried it since I was curios (to make it work I forced Eyja Alter as a favourite operators meaning the OCR will fail (as I have Eyja Alter))
> 
> Here a subtaskerror happens and it waits quite a lot, but nothing important as then it continues and it correctly selectes the medic section. It correctly OCRs the names, E2 rank is good enough with the 0.7 threshold (lowest score is .77 highest is .81)
> 
> Log error

Hi there,

> Here a subtaskerror happens and it waits quite a lot, but nothing important as then it continues and it correctly selectes the medic section.

Yes, there are several bugs to be fixed...

```json5
"UseSupportUnit-SelectRole": {
    "doc": "模版任务: 招募助战干员时通过点击浅色背景的职业图标切换职业",
    "template": "empty.png",
    "roi": [20, 93, 73, 608],
    "action": "ClickSelf",
    "next": ["UseSupportUnit-Role@NextAfterLoadingText"] // need to add "UseSupportUnit-Role#next"
},
```
Without a loadingText, we get stuck here.

And there is some logic mistakes.

```
[2024-11-05 13:06:48.606][ERR][Px4134][Tx3584] asst::UseSupportUnitTaskPlugin::try_add_support_unit_for_role | Fail to analyze support list
[2024-11-05 13:06:48.606][TRC][Px4134][Tx3584] asst::UseSupportUnitTaskPlugin::try_add_support_unit_for_role | leave, 17776 ms
```

Here `Fail to analyze support list`  does not necessarily mean any OCR or template match issue... It is just...
I forget to reset some intermediate cache variable...

I will fix them in the next PR, and will finish this functionality ASAP so that you can enjoy it once the new SupportUnit system comes online for EN.

Thanks for testing again!


Cheers,

**Comment by Alan-Charred** [comment]
It is actually surprising that OCR for Eyja Alter works.
The name is in smaller font and the roi I provide does not give sufficient "safe margins" -- at least not sufficient in my opinion.
image

Before testing it myself I have been prepared to enlarge the roi.
Now at least I do not need to worry about this.

**Comment by senyamiku1101** [comment]
How can I use this feature in Maa?

**Comment by status102** [comment]
> How can I use this feature in Maa?

you may use it in MaaCli

**Comment by Yuanlailai** [comment]
> > How can I use this feature in Maa?
> 
> you may use it in MaaCli

这应该是当前项目下的内容，并且在5.10.0更新日志里提及，但在gui中似乎没有表现出来
image

**Comment by senyamiku1101** [comment]
> > > How can I use this feature in Maa?
> > 
> > 
> > you may use it in MaaCli
> 
> 这应该是当前项目下的内容，并且在5.10.0更新日志里提及，但在gui中似乎没有表现出来 image

所以这个功能是已经推出还是仅在内部版本里有呢，我看他已经写在release的更新里了以为是加进来了

**Comment by status102** [comment]
> > > How can I use this feature in Maa?
> > 
> > 
> > you may use it in MaaCli
> 
> 这应该是当前项目下的内容，并且在5.10.0更新日志里提及，但在gui中似乎没有表现出来 image

MaaCli and MaaCore are also parts of this repo. So this pr could be placed into release note

**Pull request merged**
