### PR TITLE
ci/nightly-schedule

### PR DESCRIPTION
**Pull request by Constrat**

### CODE REVIEW

**Comment by ABA2396** [comment]
How about changing the value of limit as well? It feels like 30 iterations are completely unnecessary, and the packaging process takes a lot of time. I think 10 versions should be more than enough.

**Comment by Constrat** [comment]
Why is the limit 30 anyway? It's not like that's the fetch checkout limit.

**Comment by ABA2396** [comment]
It will generate OTA packages for 30 versions. If someone really hasn't updated for several months, they might not find an update package. However, the UI is designed to handle this by directly downloading the full package.

**Comment by Constrat** [comment]
Default limit is now 10.
The backup value is also 10 in case weird stuff is inputted.

**Pull request merged**
