### PR TITLE
fix: 修改基建 InfrastOperListTab 部分的 roi (#10999)

### LINKED ISSUE #10999: 基建换班存在干员差异时不能换班
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在换班配置文件中开启按顺序入住后，如果换班前后进驻干员存在差异，则无法选择顺序并确认，卡死在选择干员处。
推测原因：此次更新后已选中干员不会自动被排列到干员列表最前端，导致MAA无法排列顺序。

### Version

UI Version: v5.9.0-beta.1
Core Version: v5.9.0-beta.1
Build Time: 2024/10/31 23:56:49
Resource Version: 追迹日落以西
Resource Time: 2024/11/1 10:33:47

### 日志和配置文件

19:50:28处出现问题
[asst.bak.log](https://github.com/user-attachments/files/17599274/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17599276/asst.log)
[gui.json](https://github.com/user-attachments/files/17599277/gui.json)
[gui.json](https://github.com/user-attachments/files/17599293/gui.json)

### 配置信息

版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2023/‎2/‎24
操作系统内部版本	19044.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0

MUMU12 V4.1.2 1920*1080 DPI280
截图增强开启；165帧率上限；不使用GPU加速推理

### 截图或录屏

https://github.com/user-attachments/assets/5572d375-3032-4e27-a409-7b4abc53a029

### 还有别的吗？

_No response_

### PR DESCRIPTION
**Pull request by Windsland52**
fix #10999

### CODE REVIEW

**Comment by Constrat** [comment]
{04999DC8-2821-4692-B451-86713689CD38}
Global should be working fine looking at the updated ROI.

**Comment by Constrat** [comment]
Do you think unifying the ROI is doable / creates issues?

**Comment by Windsland52** [comment]
> Do you think unifying the ROI is doable / creates issues?

Due to the update of the national server infrastructure, using the original ROI range will result in operational errors.

**Comment by Constrat** [comment]
I saw the new UI for the Official, and there are still separate buttons no? So that's why I was asking for the unification of the ROI.

**Comment by Windsland52** [comment]
> I saw the new UI for the Official, and there are still separate buttons no? So that's why I was asking for the unification of the ROI.

I expanded the range of roi.

**Review by ABA2396 — APPROVED** [review]

**Comment by status102** [comment]
对了，不要使用Merge Commit

> ## ⚠️ Found 1 invalid commit(s):
> * fix: update roi for unification once more. [`c7e2aee`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c7e2aeeadf765394d0fd413fdcdff3d2e5dc5492)
> 
> Please follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format, and do not use merge commits.

这个就是因为使用Merge Commit所以弹警告

**Comment by Windsland52** [comment]
> 对了，不要提交Merge Commit
> 
> > ## ⚠️ Found 1 invalid commit(s):
> > 
> > * fix: update roi for unification once more. [`c7e2aee`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c7e2aeeadf765394d0fd413fdcdff3d2e5dc5492)
> > 
> > Please follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format, and do not use merge commits.
> 
> 这个就是因为使用Merge Commit所以弹警告

好的

**Pull request merged**
