### PR TITLE
chore: roguelike navigation for YostarJP

### PR DESCRIPTION
**Pull request by Manicsteiner**
Revert #8769 for YostarJP only

### CODE REVIEW

**Comment by Constrat** [comment]
@Manicsteiner The change was for all clients? I'm thinking the same issue should happen with all globals yes?

**Comment by Manicsteiner** [comment]
Yes, this change has been made to all Yostar servers, but you need to check out the new text section by yourself. Whats else, score of `Roguelike@IntegratedStrategies.png` is only around 0.75, and I am not sure why.

**Comment by Constrat** [comment]
Well EN is still behind as the update should drop with Shu Event yes so in 8 hours

**Comment by Constrat** [comment]
> Yes, this change has been made to all Yostar servers, but you need to check out the new text section by yourself. Whats else, score of `Roguelike@IntegratedStrategies.png` is only around 0.75, and I am not sure why.

It's so small that the minimal change reduces the score by quite a lot?

**Comment by Manicsteiner** [comment]
Its score dropped to around 0.55 at first today, but when I tried to replace it with a new one and swap it back to compare, it became 0.99. It's weird. Maybe it's due to caching.
[asst-rg-0.55.log](https://github.com/user-attachments/files/16448416/asst-rg-0.55.log)
[asst.log](https://github.com/user-attachments/files/16448419/asst.log)
just search `Roguelike@IntegratedStrategies.png`

无标题
Tested with red dot, it shouldn't matter

**Pull request merged**
