### PR TITLE
feat: YostarKR Reclamation2

### PR DESCRIPTION
**Pull request by HX3N**

### CODE REVIEW

**Comment by Constrat** [comment]
Did you notice any ROI that need fixing / tweaking?

**Comment by HX3N** [comment]
> Did you notice any ROI that need fixing / tweaking?

I just tested the normal mode, and it seems that we don't need to tweak the roi.

**Comment by Constrat** [comment]
> I just tested the normal mode, and it seems that we don't need to tweak the roi.

I am ready for the worst possible string display in the international :)

**Comment by HX3N** [comment]
KR also needs to be modified 😭

**Comment by Constrat** [comment]
Yeah I think all Yostar servers.
They changed the schedule compared to Official and Bilibili. But my question remains valid.
Since reclamation is a perma mode now, why would they need to shove it in your face? When they could have just put the banner, instead of replacing and switching everything.

**Pull request merged**
