### PR TITLE
feat: close inactive issues

### PR DESCRIPTION
**Pull request by Constrat**
ref: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9853#issuecomment-2243230911

`exempt-issue-labels`  can be used to skip (for example) `MAA Team`  issues, or any issue that has a specific label, plus the custom made label `keep-open`, in case we want to use that.

### CODE REVIEW

**Comment by zzyyyl** [comment]
It's annoying :laughing:

**Comment by Constrat** [comment]
We'll to reach 1k issues 😢

**Review by zzyyyl — APPROVED** [review]

**Comment by Rbqwow** [comment]
I wonder which time zone github bot uses 👀

**Comment by Constrat** [comment]
UTC -> GMT 0

**Comment by Constrat** [comment]
I've been rate limited. Going to have to wait some time. For now I'll just increase the cron.

**Comment by dantmnf** [comment]
👀 Well, it's a good way to tell people "stop opening issues here".

**Pull request merged**
