### PR TITLE
feat: 增加任务截图插件

### PR DESCRIPTION
**Pull request by zzyyyl**
link to #6966 
link to #6975 (this PR is not a fix for it, but to add debug screenshots for similar issues)

这个插件可以被用在任意 Task，现在只有 RoguelikeTask 注册了

### CODE REVIEW

**Comment by Constrat** [comment]
So it will take a screen of what's in `next`?
Looks very scalable also for other debugging purposes.

**Comment by Constrat** [comment]
So it will take a screen of what's in `next`?
Looks very scalable also for other debugging purposes.

**Comment by Constrat** [comment]
Misclick

**Comment by Constrat** [comment]
Something like this?
Let's just hope `next` works without having to copy the task from the CN.

**Comment by zzyyyl** [comment]
@Constrat
I think it's better not to save screenshots of the Trader Store in the release (for all users), you can add them locally if you need to.

see e4f8f1839ba1f3c15b52abbaf8d99aae28daf99e

**Comment by Constrat** [comment]
The idea as to have them only for debug users

**Comment by Lancarus** [comment]
I agree to Constrat. It may be mainly used by debug users. 
Could it run just in debug mode or beta version？
And It may be used in other function or situation，not only in roguelike mode？

**Comment by status102** [comment]
感觉可以按照检查更新的版本，如果是内测或者公测就启用。

**Comment by zzyyyl** [comment]
现在有两个截图，一个是 release 下的截图，一个是 存在 "DEBUG" 或者 "DEBUG.txt" 时的额外截图

**Review by Constrat — APPROVED** [review]

**Comment by zzyyyl** [comment]
重构了一下：）

现在这个插件可以被用在任意 Task，不过现在只有 RoguelikeTask 注册了

**Comment by Lancarus** [comment]
但是为啥要在商店加截图

**Review by Lancarus — APPROVED** [review]

**Comment by Constrat** [comment]
> 但是为啥要在商店加截图，商店现在应该没啥bug？

Some store items names have two lines.
The OCR algorithm still has no way to interprent
`texttext\ntexttext`

**Comment by Lancarus** [comment]
> Some store items names have two lines. The OCR algorithm still has no way to interprent `texttext\ntexttext`
> 
> Because of this I have to know how all the items are rendered in the store, to regex them I haven't found a solution yet apart from this...

I see...That's really a problem.Localization is really a troublesome job.
Fortunately, we do have you.

**Pull request merged**
