### PR TITLE
Release v3.9.0-beta.6: 新版肉鸽重构及适配完成；自动抄作业优化

### LINKED ISSUE #167: 肉鸽自定义选人方法
肉鸽选人是可配置的，但是由于时间关系还没来得及做到界面上

有需要的话可以手动修改 `resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段~

Tips: 这个文件每个版本都或多或少有差异，请不要将老版本的文件直接替换到新版本上来用，会出现一些莫名其妙的问题

image

同一个问题的 issue 比较多，我先统一关了，后续这个问题的新方案在这里跟进进展_(:з」∠)_

### LINKED ISSUE #175: 肉鸽选人界面没有移动或无法移动导致选人异常
干员招募图
干员招募图2
干员顺位

肉鸽初次选择干员时，由于干员山在干员列表第三列，无法识别和选择干员山，转而选择排序后一位的干员煌

### LINKED ISSUE #192: 一些肉鸽模式的改进建议
一、肉鸽招募相关
1.碰到肉鸽招募界面时检测第一个干员的招募希望是不是0，再按列表ocr选择干员。这样遇到免费干员和免费进阶的不会放弃
07`6IIF9)37XHJ06ABE48~A
2.第一页内没有列表干员的时候滑到最右边识别选择三星备选干员
3.拿到收藏品和一些不期而遇时间要检测几秒是否到达招募界面

二、商店相关
如果第一层没有存钱的按钮，可以考虑随机买一些商品，（识别绿色三角，可以顺带做一些花费源石锭的月度任务啥的）

三、干员技能
在没有指定那个干员优先配几技能的情况下能否在开始战斗界面按顺序快速点，以保障干员优先用高级的技能
V$}BUTE3457H6Z`T3U0{Z@M
后续如果准备写哪个干员优先指定几技能可以通过在该界面ocr干员名字，点击相对技能位置确定

### LINKED ISSUE #194: 肉鸽 干员名字不完全匹配
计划招募“克洛丝”，但给招了“寒芒克洛丝”

### LINKED ISSUE #224: 自动肉鸽时，未跳过鸭爵战斗，可调整为不战斗，效率会高很多。
另一个小问题：招募干员时我的煌总是识别不了。

### LINKED ISSUE #239: 有关刷投资的肉鸽战斗结束之后拿什么的建议
其实个人觉得还是拿钱就够了。
毕竟只是刷投资，速度肯定越快越好，而且开局的人已经够打一层，没有必要再选人。
而且也可以避免因为拿剧目卡死造成的bug。

### LINKED ISSUE #253: 肉鸽模式：优先解锁收藏品
如题，肉鸽添加解锁收藏品模式，尽量往后打，在有选择的地方（馈赠，商店等）尽量选择未获取过的收藏品

### LINKED ISSUE #364: 感化重装刮痧卡死
QQ图片20220420161119

### LINKED ISSUE #390: 肉鸽选干员时异格与原干员不分
在config.json中配置肉鸽招募选择有异格的干员，
且同时拥有原干员和异格干员，会出现选择异格干员而不是原干员的情况
如配置为：克洛丝
实际会选到：寒芒克洛丝
炎熔也会出现同样问题

### LINKED ISSUE #554: 肉鸽功能建议
因为看到issue区很多人说要支持更加“聪明”的肉鸽打法，是不是可以推出一个接口客制化每一关的打法。这样工程量或许会更小
等研究下代码后试试加功能（其实肉鸽次数选择的支持也挺需要的

### LINKED ISSUE #555: 肉鸽打本提议
建议采用泥岩，泥岩带二技能基本solo前两层，现在的作战太蠢了（）

### LINKED ISSUE #576: v3.3.2版本肉鸽没有二倍速
日志文件太大了所以整了压缩包
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8768499/asst.zip)
软件界面一直很正常但每次窥屏的时候都只有一倍速，用的夜神模拟器
image

### LINKED ISSUE #577: 肉鸽选择干员无法识别山
使用Linux自行编译，master分支和dev分支均实验过，山就在第一个，但是别结果中没有
```C
AsstAppendTask(ptr, "Roguelike", R"(
    {
        "opers": [
            {
                "name": "山",
                "skill": 2,
                "skill_usage": 2
            },
            {
                "name": "梓兰"
            },
            {
                "name": "芙蓉"
            }
        ]
    }
    )");
```
screenshot
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8768595/asst.log)

### LINKED ISSUE #585: 肉鸽第一关-开局就跪了，医疗干员芙蓉摆放的朝向有问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/8785818/asst.log)

在肉鸽第一关的时候，因为落地医疗干员芙蓉的摆放位置朝向发生了问题，导致开局就跪了。目前尚不清楚是医疗干员皮肤导致，还是其他原因。

QQ图片20220527180801

### PR DESCRIPTION
**Pull request by MistEO**
✿✿ヽ(°▽°)ノ✿

fix #585
fix #577
fix #576
fix #390
fix #364
fix #253
fix #194
fix #192

close #555
close #554
close #239
close #224
close #175
close #167

### CODE REVIEW

**Comment by MistEO** [comment]
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/585
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/577
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/576
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/390
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/364
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/253
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/194
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/192



close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/555
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/554
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/239
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/224
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/175
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/167

**Comment by MistEO** [comment]
close #555
close #554
close #239
close #224
close #175
close #167

**Comment by MistEO** [comment]
@LiamSho 为啥 close 没用，教教 QAQ

**Comment by LiamSho** [comment]
> @LiamSho 为啥 close 没用，教教 QAQ

要写在最顶上那条里面

能连上必须要求 #xxx 在 Commit Message 里面

PR 的标题和第一个框框里面的内容是会写进 Merge 的那条 Commit 里面的

你也可以在对应的那个 Commit 的 Commit Message 里面写 close `git commit -m "fix.xxxxxx close #???"`，这样包含这条 Commit 的 PR 合并之后也能自动关掉 #???

**Comment by MistEO** [comment]
> 框里面的内容是会写进 Merge 的那条 Commit 里面的

好耶！

**Comment by MistEO** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/projects/1#card-82248400

**Pull request merged**
