### PR TITLE
chore: convert workflow input values to int

### PR DESCRIPTION
**Pull request by Constrat**

### CODE REVIEW

**Comment by Constrat** [comment]
nvm. I'm not built for this

**Comment by Constrat** [comment]
Oh this seems to work

**Comment by Constrat** [comment]
Now it's working correctly. Tested with:
- default values 
    - web 
    - mobile app
- custom value 
    - web 
    - mobile app

**Comment by ABA2396** [comment]
I tried expr and it doesn't handle non-ints, I'll see what I can do about that.

**Comment by Constrat** [comment]
Expr is not good. Printf seems to work but it's a huge instructions. In the end regexing seems good :)

**Comment by Constrat** [comment]
And with this it should be good to merge (squash as there's too many test commits)

**Comment by ABA2396** [comment]
image
It looks good; I like it.
By the way, where do I access the action on the phone? I couldn’t find it after searching for a while.

**Comment by ABA2396** [comment]
Well, it looks like I didn't update it XD

**Comment by Constrat** [comment]
:O

**Pull request merged**
