### PR TITLE
feat: add multi external notifications

### PR DESCRIPTION
**Pull request by Sieluna**
- [x] #7987
- [x] #7999

Procedural:

1. Get the bot token from discord application.

1.1 Create application at https://discord.com/developers/applications.

1.2 Go to `Bot` tab at https://discord.com/developers/applications/{your_app}/bot.

1.3 Get your bot token (reset or visible first visit).

2. Get your user id from discord web, https://discord.com/channels/@me.

2.1 Visit your `Settings-> Advance Settings`.

2.2 Enable the `Developer mode`.

2.3 Back to home page click your avatar.

2.4 Click the last row at the pop up panel called `Copy user id`.

3. Go to your Maa GUI.

3.1 Fill up the required info:

4. Test by click `Test` button.

### CODE REVIEW

**Comment by Sieluna** [comment]
Any progress?

**Review by ABA2396 — APPROVED** [review]

**Comment by status102** [comment]
语言文件需要添加所有语言的，缺了韩文、日文和繁中

**Comment by Sieluna** [comment]
> 语言文件需要添加所有语言的，缺了韩文、日文和繁中

Done.

**Review by ABA2396 — APPROVED** [review]
cc @status102

**Pull request merged**
