### PR TITLE
feat: visiting only once a day logic and gui

### PR DESCRIPTION
**Pull request by Constrat**
If I remember correctly this was something that @status102 proposed a while back. (Can't remember the issue #) I had some time so I wrote some stuff. I tested everything and it's working as expected
(Since it's basically just a copy of the CreditFightTask).

If changes are needed, feel free to directly commit (no git push --force please :)

### CODE REVIEW

**Comment by ABA2396** [comment]
这样有可能第一次访问完但不满10个人吧，要么做成可选项让用户自己选要不要跑第二次

**Comment by Constrat** [comment]
The visiting task is already automatic in the way that it will stop when you get no more credits. If it happens today, you will skip till the reset, where MAA will finally do it no?

**Comment by ABA2396** [comment]
Only get credits for visiting friends who are exchanging leads, some people may not have enough friends or none of their friends are exchanging leads at all

**Comment by Constrat** [comment]
Oh I see. Meaning only once a day can not be enough for some players.

**Comment by ABA2396** [comment]
> How about a toggle that allows "only once a day"

Exactly.

**Comment by Constrat** [comment]
image
@ABA2396 There's something I'm hating. Why aren't they all equally spaced? XD
The middles ones are 24 apart, while the outside ones are 26.

**Comment by Constrat** [comment]
image
Chosen this one for now, graphically change it however you want to

**Comment by ABA2396** [comment]
Maybe we could make this whole mission just one run? What's the point of shopping multiple times when you can only visit friends and fight once

**Comment by status102** [comment]
> Maybe we could make this whole mission just one run? What's the point of shopping multiple times when you can only visit friends and fight once

同样用那个creditFight的计时器？

**Comment by Constrat** [comment]
> What's the point of shopping multiple times when you can only visit friends and fight once

When you run MAA multiple times a day, it can happen that in the base infrastructure you finish a clue exchange receiving 210 credits. They can easily overflow hence why I never considered it.
I think the credit shopping is ok like this.

**Comment by Constrat** [comment]
For now let's just merge this, to separate feats.
In case credit shopping is required only once, we can always add it later

**Comment by ABA2396** [comment]
> What the actual fuck is the issue here. I'm literally adding a new line, how's this a merge conflict

image
To maintain a linear commit history, please avoid using force push and direct merges when possible. Instead, consider using rebase to keep your branch up to date. If a merge is necessary, you can squash commits before merging into the main branch to keep the history clean. This approach helps prevent conflicts and ensures a more manageable commit history.

**Comment by Constrat** [comment]
Even in a personal branch? Considering we are completely blocking merging / updating from the main branch to clean the commits/tweak them. Force pushing seems the only way.

**Comment by ABA2396** [comment]
Regarding this issue, I'm not entirely sure how this record came about. It could be due to a merge operation you performed, or someone might have done a force push on the dev branch (which is generally not allowed). If you are certain that no one else has been working on your branch, then force pushing should be fine. However, if possible, it's best to avoid using force pushes, especially in team environments, to maintain a clean and consistent history.

**Comment by ABA2396** [comment]
We're not completely prohibiting merges from the main branch; merging dev is allowed if necessary.

**Comment by Constrat** [comment]
I need to learn rebasing.
The thing is I didn't want to bring all the changes from dev to this branch.

**Pull request merged**
