### PR TITLE
chore: 增加 TaskSorter 脚本对 tasks.json 进行排序

### PR DESCRIPTION
**Pull request by zzyyyl**
部分代码参考 `tools/ResourceUpdater/Tasks_Sorter.py`

### CODE REVIEW

**Comment by MistEO** [comment]
也加到 CI 里？

**Comment by zzyyyl** [comment]
可以，但先看看有没有问题.jpg

**Comment by MistEO** [comment]
能跑就是好脚本（

**Review by MistEO — APPROVED** [review]

**Comment by Constrat** [comment]
@zzyyyl [Tasks_Sorter.py](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/984a30cb2648fd174f72b2457abaeed32b603989/tools/ResourceUpdater/Tasks_Sorter.py) isn't this sort of a duplicate?

**Comment by Constrat** [comment]
smoke-testing for a python script? 😆

**Review by Constrat — APPROVED** [review]

**Pull request merged**
