### PR TITLE
feat: Add connection config for waydroid emulator

### PR DESCRIPTION
**Pull request by leolbyy**
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9396

Tested on raspberry pi 5 (Debian 12) with waydroid 1.4.2

### CODE REVIEW

**Comment by aleck099** [comment]
Is it OK to execute `[Adb] -s [AdbSerial] shell am start-activity --windowingMode 4 [Intent]` on all devices? Since it's not a feature of waydroid, but a feature named "multiwindow" in Android 7.0

**Comment by Rbqwow** [comment]
> Is it OK to execute `[Adb] -s [AdbSerial] shell am start-activity --windowingMode 4 [Intent]` on all devices? Since it's not a feature of waydroid, but a feature named "multiwindow" in Android 7.0

https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9620#issuecomment-2223299701

别的模拟器还没测试 各家有可能都不一样

**Comment by horror-proton** [comment]
> 别的模拟器还没测试 各家有可能都不一样

这就是个单独的配置, 用 Waydroid 的选这个就行, 不影响默认的 (

**Comment by Rbqwow** [comment]
> > 别的模拟器还没测试 各家有可能都不一样
> 
> 这就是个单独的配置, 用 Waydroid 的选这个就行, 不影响默认的 (

这样肯定可以 不能改全局的

**Pull request merged**
