### PR TITLE
feat: SSS#2 YostarEN implementation

### PR DESCRIPTION
**Pull request by Constrat**

### CODE REVIEW

**Comment by Constrat** [comment]
```js
[2023-11-18 18:29:42.555][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":0,"to_be_recognized":["SSSHalfTimeDropsBegin"]},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:42.555][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze SSSHalfTimeDropsBegin
[2023-11-18 18:29:42.555][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancel.png score: 0.999028 rect: [ 148, 332, 46, 46 ] roi: [ 148, 332, 46, 46 ]
[2023-11-18 18:29:42.555][INF][Px106b8][Txf32c] exec times exceeded the limit {"class":"asst::ProcessTask","details":{"exec_times":0,"limit_type":"pre","max_times":0,"task":"SSSHalfTimeDropsBegin"},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"what":"ExceededLimit"}
[2023-11-18 18:29:42.555][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskExtraInfo {"class":"asst::ProcessTask","details":{"exec_times":0,"limit_type":"pre","max_times":0,"task":"SSSHalfTimeDropsBegin"},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1","what":"ExceededLimit"}
[2023-11-18 18:29:42.555][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 0 ms
[2023-11-18 18:29:42.555][INF][Px106b8][Txf32c] Get drops [无需增调干员, 狙击, 术士, 先锋, 重装, 辅助, 战备激活阀, 增活针剂]
[2023-11-18 18:29:42.555][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:42.556][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDropsBegin"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:42.556][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsBegin
[2023-11-18 18:29:42.556][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancel.png score: 0.999028 rect: [ 148, 332, 46, 46 ] roi: [ 148, 332, 46, 46 ]
[2023-11-18 18:29:42.556][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsBegin"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:42.556][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsBegin"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:42.556][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:43.057][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:43.057][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDrops","0000021C36082150@SSSHalfTimeDropsCancel"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:43.401][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 344 ms , stdout size: 2196197 , socket size: 0
[2023-11-18 18:29:43.422][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDrops
[2023-11-18 18:29:43.495][TRC][Px106b8][Txf32c] asst::WordOcr [{ XXXXX: [ 336, 37, 78, 13 ], score: 0.571662 }, { XXX: [ 512, 34, 66, 20 ], score: 0.631382 }, { Jusk: [ 161, 67, 31, 15 ], score: 0.852868 }, { Bagpipe: [ 330, 67, 63, 17 ], score: 0.997001 }, { Platinum: [ 504, 65, 70, 19 ], score: 0.997244 }, { Mai: [ 690, 70, 20, 11 ], score: 0.689026 }] by OCR Pipeline , cost 72 ms
[2023-11-18 18:29:43.500][TRC][Px106b8][Txf32c] Proced []
[2023-11-18 18:29:43.500][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancel
[2023-11-18 18:29:43.502][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancel.png score: 0.999027 rect: [ 148, 332, 46, 46 ] roi: [ 100, 284, 145, 145 ]
[2023-11-18 18:29:43.502][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsCancel"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:43.502][TRC][Px106b8][Txf32c] minitouch click: (267, 537)
[2023-11-18 18:29:43.603][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsCancel"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:43.603][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:44.104][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:44.104][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDropsCancelConfirm"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsCancel","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:44.380][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 276 ms , stdout size: 1579499 , socket size: 0
[2023-11-18 18:29:44.400][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancelConfirm
[2023-11-18 18:29:44.400][INF][Px106b8][Txf32c] asst::TemplResource::get_templ lazy load SSSHalfTimeDropsCancelConfirm.png
[2023-11-18 18:29:44.404][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancelConfirm.png score: 0.998136 rect: [ 794, 477, 101, 39 ] roi: [ 716, 410, 254, 163 ]
[2023-11-18 18:29:44.404][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsCancelConfirm"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsCancel","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:44.404][TRC][Px106b8][Txf32c] minitouch click: (1269, 744)
[2023-11-18 18:29:44.505][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"ClickSelf","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsCancelConfirm"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsCancel","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:44.505][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 1949 ms
[2023-11-18 18:29:44.505][TRC][Px106b8][Txf32c] asst::SSSBattleProcessTask::do_strategic_action | leave, 1950 ms
[2023-11-18 18:29:44.861][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 355 ms , stdout size: 2806823 , socket size: 0
[2023-11-18 18:29:44.887][TRC][Px106b8][Txf32c] asst::BattlefieldMatcher::pause_button_analyze count 0 threshold 200
[2023-11-18 18:29:44.889][TRC][Px106b8][Txf32c] match_templ | BattleHpFlag.png score: 0.961313 rect: [ 772, 13, 31, 34 ] roi: [ 400, 0, 650, 60 ]
[2023-11-18 18:29:44.889][TRC][Px106b8][Txf32c] asst::BattleProcessTask::check_in_battle | enter
[2023-11-18 18:29:44.889][TRC][Px106b8][Txf32c] asst::BattlefieldMatcher::pause_button_analyze count 0 threshold 200
[2023-11-18 18:29:44.891][TRC][Px106b8][Txf32c] match_templ | BattleHpFlag.png score: 0.961313 rect: [ 772, 13, 31, 34 ] roi: [ 400, 0, 650, 60 ]
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::BattleProcessTask::check_in_battle | leave, 6 ms
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::SSSBattleProcessTask::do_strategic_action | enter
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":0,"to_be_recognized":["SSSHalfTimeDropsBegin"]},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze SSSHalfTimeDropsBegin
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancel.png score: 0.991916 rect: [ 148, 332, 46, 46 ] roi: [ 148, 332, 46, 46 ]
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] exec times exceeded the limit {"class":"asst::ProcessTask","details":{"exec_times":0,"limit_type":"pre","max_times":0,"task":"SSSHalfTimeDropsBegin"},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"what":"ExceededLimit"}
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskExtraInfo {"class":"asst::ProcessTask","details":{"exec_times":0,"limit_type":"pre","max_times":0,"task":"SSSHalfTimeDropsBegin"},"first":["SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1","what":"ExceededLimit"}
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 0 ms
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] Get drops [无需增调干员, 狙击, 术士, 先锋, 重装, 辅助, 战备激活阀, 增活针剂]
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDropsBegin"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsBegin
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] match_templ | SSSHalfTimeDropsCancel.png score: 0.991916 rect: [ 148, 332, 46, 46 ] roi: [ 148, 332, 46, 46 ]
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskStart {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsBegin"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:44.896][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskCompleted {"class":"asst::ProcessTask","details":{"action":"DoNothing","algorithm":"MatchTemplate","exec_times":1,"max_times":2147483647,"task":"SSSHalfTimeDropsBegin"},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:44.896][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:45.397][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:45.397][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDrops","0000021C36082150@SSSHalfTimeDropsCancel"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:45.773][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 376 ms , stdout size: 3700434 , socket size: 0
[2023-11-18 18:29:45.805][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDrops
[2023-11-18 18:29:45.838][TRC][Px106b8][Txf32c] asst::WordOcr [{ SAS: [ 0, 0, 897, 88 ], score: 0.271928 }] by OCR Pipeline , cost 32 ms
[2023-11-18 18:29:45.839][TRC][Px106b8][Txf32c] Proced []
[2023-11-18 18:29:45.839][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancel
[2023-11-18 18:29:45.840][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 944 ms
[2023-11-18 18:29:45.840][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:46.341][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:46.341][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:46.341][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":1,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDrops","0000021C36082150@SSSHalfTimeDropsCancel"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:46.742][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 401 ms , stdout size: 3707540 , socket size: 0
[2023-11-18 18:29:46.774][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDrops
[2023-11-18 18:29:46.805][TRC][Px106b8][Txf32c] asst::WordOcr [{ EES: [ 0, 0, 897, 88 ], score: 0.297856 }] by OCR Pipeline , cost 31 ms
[2023-11-18 18:29:46.806][TRC][Px106b8][Txf32c] Proced []
[2023-11-18 18:29:46.806][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancel
[2023-11-18 18:29:46.807][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 466 ms
[2023-11-18 18:29:46.807][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:47.309][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:47.309][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:47.309][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":2,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDrops","0000021C36082150@SSSHalfTimeDropsCancel"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:47.771][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 463 ms , stdout size: 3992446 , socket size: 0
[2023-11-18 18:29:47.807][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDrops
[2023-11-18 18:29:47.838][TRC][Px106b8][Txf32c] asst::WordOcr [{ SHES: [ 0, 0, 897, 88 ], score: 0.315881 }] by OCR Pipeline , cost 31 ms
[2023-11-18 18:29:47.839][TRC][Px106b8][Txf32c] Proced []
[2023-11-18 18:29:47.839][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancel
[2023-11-18 18:29:47.841][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 532 ms
[2023-11-18 18:29:47.841][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:48.342][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:48.342][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
[2023-11-18 18:29:48.342][INF][Px106b8][Txf32c] {"class":"asst::ProcessTask","details":{"cur_retry":3,"retry_times":3,"to_be_recognized":["0000021C36082150@SSSHalfTimeDrops","0000021C36082150@SSSHalfTimeDropsCancel"]},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0}
[2023-11-18 18:29:48.792][INF][Px106b8][Txf32c] Call ` C:\Users\David\Downloads\MAA\adb\adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 450 ms , stdout size: 3999012 , socket size: 0
[2023-11-18 18:29:48.826][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDrops
[2023-11-18 18:29:48.855][TRC][Px106b8][Txf32c] asst::WordOcr [{ SEAS: [ 0, 0, 897, 88 ], score: 0.246636 }] by OCR Pipeline , cost 27 ms
[2023-11-18 18:29:48.856][TRC][Px106b8][Txf32c] Proced []
[2023-11-18 18:29:48.856][TRC][Px106b8][Txf32c] asst::PipelineAnalyzer::analyze 0000021C36082150@SSSHalfTimeDropsCancel
[2023-11-18 18:29:48.858][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | leave, 515 ms
[2023-11-18 18:29:48.858][TRC][Px106b8][Txf32c] ready to sleep 500
[2023-11-18 18:29:49.359][TRC][Px106b8][Txf32c] end of sleep 500
[2023-11-18 18:29:49.359][INF][Px106b8][Txf32c] Assistant::append_callback | SubTaskError {"class":"asst::ProcessTask","details":{},"first":["0000021C36082150@SSSHalfTimeDropsBegin"],"pre_task":"0000021C36082150@SSSHalfTimeDropsBegin","subtask":"ProcessTask","taskchain":"SSSCopilot","taskid":0,"uuid":"4052f02112be81d1"}
[2023-11-18 18:29:49.359][TRC][Px106b8][Txf32c] asst::ProcessTask::on_run_fails | enter
[2023-11-18 18:29:49.359][TRC][Px106b8][Txf32c] asst::ProcessTask::on_run_fails | leave, 0 ms
[2023-11-18 18:29:49.359][TRC][Px106b8][Txf32c] asst::ProcessTask::_run | enter
```
Every time there's a halfdrop event. It will complete correctly the sequence (canceling and returning to battle) but as soon as that's done. It will SOMEHOW detect the flag again and repeat the action (which will not work as the interface has changed) and before. It was trying 20 TIMES! It was a lot of wasted time (because the stage was running, but MAA wasn't changing operators / using skills etc). I've lowered the retry times to only 3.
Unfortunately it's not the correct solution, but only a "patch". I've tried modifying the template for the flag but it seems like it takes two fast screens back to back and when the animation is closing the interface, it will still detect the flag and start the algorithm. @MistEO @ABA2396 if big brothers have any idea on where this could from, I would appreciate it. as I don't think lowering the retry times is the correct solution.

**Comment by Constrat** [comment]
@junyihan233 Hey, sorry to bother, I've been working on the Mama John's (约翰老妈在建地块) SSS json and I noticed that Ch'En alter never uses her skill. And in fact the json is made in a way that her skill_usage is `0` meaning it will only follow the `actions` field. But for Ch'en alter, the only time it's used is in the last stage (there are many times where the skill should be used) so I'm wondering if it's wanted, it's a mistake or is there any specific reason as to why the skill shouldn't activate

**Comment by Constrat** [comment]
Well, with this I think I fixed everything "strange" that I've encountered, even managed to add a bit more failsafes in the algorithms

**Comment by Constrat** [comment]
Where the fuck is the conflict. That file has already been moved bruh.

**Comment by Constrat** [comment]
bruuh

**Comment by junyihan233** [comment]
你好，我在制作这个脚本的时候，maa的技能识别还是有些问题，当时并不能很好地识别假日威龙陈的技能，无论 "skill_usage"设定成1还0，都会自动释放。你这样修改是可以的，但是在第六关的“action”里，你有必要把假日威龙陈的技能切换成0，因为我设置了水陈的技能会在击杀数56的时候释放。
Hi, when I was working on this script, maa still had some problems with skill recognition. At that time, it did not recognize the skill of holiday Veyloong Chen very well. Whether "skill_usage" was set to 1 or 0, it would be automatically released. You can modify it this way, but in the sixth level of "action", you need to change the holiday dragon Chen's skill to 0, because I set the Water Chen's skill to release when the kill number is 56.

**Pull request merged**
