### PR TITLE
fix: 修复日服基建换班卡在宿舍

### LINKED ISSUE #7063: 日服基建换班功能 新版本更新后宿舍功能故障
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

基建进宿舍功能后会卡在选择未配属的这个页面不动，然后报错跳过。
顺带一提火龙黑角和麒麟夜刀的基建分配功能也不好用，会认不出来，但是猫猫能认出来。

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13112809/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13112812/gui.log)

### 截图

image

### 还有别的吗？

逍遥模拟器

### PR DESCRIPTION
**Pull request by MejiroSilence**
fix #7063 

`InfrastFilterMenuNotStationedButton` 的分数低了, 只有 0.777372

### CODE REVIEW

**Comment by Constrat** [comment]
Score seems too low considering how small the image is. Have you tried taking a new .png and testing it?

**Comment by MejiroSilence** [comment]
i tried taking a new png just now , it works and can get a high score. so is it better to take a new png to replace it?

> [2023-10-25 06:39:13.114][INF][Px8090][Tx4374] asst::TemplResource::get_templ lazy load InfrastFilterMenuNotStationedButton.png
> [2023-10-25 06:39:13.123][TRC][Px8090][Tx4374] match_templ | InfrastFilterMenuNotStationedButton.png score: 0.999999 rect: [ 358, 338, 158, 45 ] roi: [ 308, 288, 258, 145 ]

**Comment by MejiroSilence** [comment]
by the way, if i get png with the default roi(amplified 300, 300, 250, 150, i set original as  350, 350, 150, 50) which used by cn, jp and also en, it seems that the pngs looks not good.
especially in jp, there is only half part of the "属"  in the png file. and there is some white area outside the button.
png with default roi in cn:
Screenshot_2023 10 25_07 24 59 758_300,300,250,150

png with default roi in jp:
Screenshot_2023 10 24_22 17 21 924_300,300,250,150

**Comment by zzyyyl** [comment]
推错了吧）

**Comment by Constrat** [comment]
This seems very strange

**Comment by zzyyyl** [comment]
> by the way, if i get png with the default roi(amplified 300, 300, 250, 150, i set original as 350, 350, 150, 50) which used by cn, jp and also en, it seems that the pngs looks not good. especially in jp, there is only half part of the "属" in the png file. and there is some white area outside the button. png with default roi in cn: Screenshot_2023 10 25_07 24 59 758_300,300,250,150
> 
> png with default roi in jp: Screenshot_2023 10 24_22 17 21 924_300,300,250,150

只要整个 template 在 roi 里面就可以被匹配到的，不一定是正中心啊）
对于上面举的例子，只要 [300, 300, 250, 150] 截出来的图包含模板图片就行了，不一定非得是 [350, 350, 150, 50]

**Comment by MejiroSilence** [comment]
> 是不是推错了，现在这个 pr 的 commit 看着不太对

我傻了(

**Review by MistEO — APPROVED** [review]
LGTM.

**Comment by Constrat** [comment]
If you only modify the image, without changing the ROI. Issues might happen again. You pointed out that the ROI was wrong. If you can, fox it :)

**Comment by zzyyyl** [comment]
感觉 InfrastFilterMenuNotStationedButtonAlreadyClicked 这张图可能也得改改（？

**Pull request merged**
