### PR TITLE
chore: YoStarKR modifiy tasks.json

### PR DESCRIPTION
**Pull request by HX3N**
remove StageEncounterOptionFree as it is no longer used
Added Mizuki@Roguelike@DataTraceback to fix screen stuck issue on DataTraceback screen.

### CODE REVIEW

**Comment by Constrat** [comment]
> Added Mizuki@Roguelike@DataTraceback to fix screen stuck issue on DataTraceback screen.

Mizuki@Roguelike@DataTraceback should be an image

**Comment by HX3N** [comment]
@Constrat 

I'm not sure why, but when checked locally, it seems to be functioning correctly. According to the logs, it recognizes 'DataTraceBack.png' and then performs the action 'ClickRect.'

The method may have been incorrect, but after testing for two days, the issue of getting stuck on the 'DataTraceBack' screen in the Mizuki Roglike seems to have been resolved.

```
[2024-01-14 14:48:09.232][INF][Pxbfd00][Txa961c] Call ` C:\Program Files\BlueStacks_nxt\HD-Adb.exe -s 127.0.0.1:5555 exec-out "screencap | gzip -1" ` ret 0 , cost 303 ms , stdout size: 1103582 , socket size: 0
[2024-01-14 14:48:09.247][TRC][Pxbfd00][Txa961c] asst::PipelineAnalyzer::analyze Mizuki@Roguelike@DataTraceback
[2024-01-14 14:48:09.251][TRC][Pxbfd00][Txa961c] match_templ | Mizuki@Roguelike@DataTraceback.png score: 0.999405 rect: [ 106, 327, 143, 52 ] roi: [ 56, 277, 243, 152 ]
[2024-01-14 14:48:09.251][INF][Pxbfd00][Txa961c] Assistant::append_callback | SubTaskStart 
{
    "class": "asst::ProcessTask",
    "details": {
        "action": "ClickRect",
        "algorithm": "MatchTemplate",
        "exec_times": 1,
        "max_times": 2147483647,
        "result": {
            "score": 0.999405
        },
        "task": "DataTraceback"
    },
    "first": [
        "Mizuki@Roguelike@Begin"
    ],
    "pre_task": "Mizuki@Roguelike@GamePassSkip1Confirm",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 5,
    "uuid": "c07d4e6d7a7eb88d"
}
[2024-01-14 14:48:09.251][TRC][Pxbfd00][Txa961c] minitouch click: (1212, 48)
[2024-01-14 14:48:09.352][INF][Pxbfd00][Txa961c] Assistant::append_callback | SubTaskCompleted
{
    "class": "asst::ProcessTask",
    "details": {
        "action": "ClickRect",
        "algorithm": "MatchTemplate",
        "exec_times": 1,
        "max_times": 2147483647,
        "result": {
            "score": 0.999405
        },
        "task": "DataTraceback"
    },
    "first": [
        "Mizuki@Roguelike@Begin"
    ],
    "pre_task": "Mizuki@Roguelike@GamePassSkip1Confirm",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 5,
    "uuid": "c07d4e6d7a7eb88d"
}
[2024-01-14 14:48:09.352][TRC][Pxbfd00][Txa961c] ready to sleep 500
[2024-01-14 14:48:09.852][TRC][Pxbfd00][Txa961c] end of sleep 500
[2024-01-14 14:48:09.852][INF][Pxbfd00][Txa961c] 
{
    "class": "asst::ProcessTask",
    "details": {
        "cur_retry": 0,
        "retry_times": 20,
        "to_be_recognized": [
            "Mizuki@Roguelike@ClickToStartPoint"
        ]
    },
    "first": [
        "Mizuki@Roguelike@Begin"
    ],
    "pre_task": "Mizuki@Roguelike@DataTraceback",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 5
}
[2024-01-14 14:48:09.852][INF][Pxbfd00][Txa961c] Assistant::append_callback | SubTaskStart 
{
    "class": "asst::ProcessTask",
    "details": {
        "action": "ClickRect",
        "algorithm": "JustReturn",
        "exec_times": 1,
        "max_times": 2147483647,
        "result": null,
        "task": "ClickToStartPoint"
    },
    "first": [
        "Mizuki@Roguelike@Begin"
    ],
    "pre_task": "Mizuki@Roguelike@DataTraceback",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 5,
    "uuid": "c07d4e6d7a7eb88d"
}
[2024-01-14 14:48:09.852][TRC][Pxbfd00][Txa961c] minitouch click: (625, 623)
[2024-01-14 14:48:09.954][TRC][Pxbfd00][Txa961c] ready to sleep 800
[2024-01-14 14:48:10.754][TRC][Pxbfd00][Txa961c] end of sleep 800
[2024-01-14 14:48:10.754][INF][Pxbfd00][Txa961c] Assistant::append_callback | SubTaskCompleted 
{
    "class": "asst::ProcessTask",
    "details": {
        "action": "ClickRect",
        "algorithm": "JustReturn",
        "exec_times": 1,
        "max_times": 2147483647,
        "result": null,
        "task": "ClickToStartPoint"
    },
    "first": [
        "Mizuki@Roguelike@Begin"
    ],
    "pre_task": "Mizuki@Roguelike@DataTraceback",
    "subtask": "ProcessTask",
    "taskchain": "Roguelike",
    "taskid": 5,
    "uuid": "c07d4e6d7a7eb88d"
}
[2024-01-14 14:48:10.754][TRC][Pxbfd00][Txa961c] ready to sleep 500
[2024-01-14 14:48:11.255][TRC][Pxbfd00][Txa961c] end of sleep 500
[2024-01-14 14:48:11.255][INF][Pxbfd00][Txa961c] 
```
this is full log from after clearing the stage until the restart

[asst-test.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13938490/asst-test.log)

**Comment by Constrat** [comment]
This is strange. It seems like the client behave differently. Why would the Official not need the specific click? While the KR needs the specific rect. It's a bit strange.
If you tested it as working, then I can't really find a reason not to merge.

**Comment by HX3N** [comment]
Screenshot_2024 01 13_15 29 45 482

If it operates normally, I understand that you need to press 'Skip' on that screen and proceed with the settlement. However, there is an issue with 'YoStarKR' where it is unable to press 'Skip' and stops at the 'Data Review' by clicking the center of the screen.

Honestly, I don't quite understand why this is happening. Even when I searched for an ISSUE, it seems that this problem is occurring only with YoStarKR.

**Comment by HX3N** [comment]
I checked about that, and originally, the GamePassSkip2.png is not present in the original image template. Phantom Logike has both GamePassSkip1.png and GamePassSkip2.png, but Mizuki Logike lacks GamePassSkip2.png.

I also tried adding GamePassSkip2.png, thinking that the issue might be due to the missing image, but it didn't resolve the problem.

**Comment by Constrat** [comment]
@HX3N Well no need to understand everything. If this works, it works.
If you can confirm this doesn't conflict with anything else, but fixes the issue you mentioned then I'm merging.

**Comment by HX3N** [comment]
@Constrat 
I have checked for any additional issues, but there were none! It seems safe to proceed with the merge

**Pull request merged**
