### PR TITLE
fix: 更改麒麟X夜刀为麒麟R夜刀

### PR DESCRIPTION
**Pull request by SherkeyXD**
作业站那边也得做全局替换

### CODE REVIEW

**Comment by Lancarus** [comment]
等#6140合完了再合这个，我把sami/recruitment.json里面重复的删掉了一段，里面有个夜刀

**Comment by Constrat** [comment]
#6195 was already having trouble. For now I just changed resource/tasks.json
This shouldn't create any conflicts.

**Comment by MistEO** [comment]
@SherkeyXD 冲突了

**Comment by SherkeyXD** [comment]
#6199

**Pull request closed without merging**
