### PR TITLE
fix: 为InfrastEnteredFlag添加延迟以避免信用通知对右上角基建提醒的遮挡

### LINKED ISSUE #9474: 基建截图添加延时，以避免信用提示遮挡右上角快速收菜提示
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 Bug（不确定的话请附上日志）

### 说说你遇到的问题？

如果在进入基建时，触发了线索收集回信用的提示，将对界面右上角的快速收菜进行遮挡，导致基建快速收菜不会执行

### 有什么好的想法？

建议对上述操作对应的基建截图操作添加2-3s左右的延时，以避免信用提示遮挡问题

### 其他内容

_No response_

### PR DESCRIPTION
**Pull request by Viel0320**
为InfrastEnteredFlag添加延迟以避免信用通知对右上角基建提醒的遮挡

 #9474

### CODE REVIEW

**Comment by Lancarus** [comment]
要加这么长延时？

**Comment by Constrat** [comment]
5000 is technically enough, but when there is no Reception notification, is definitely too much.

Anyway, in the worst-case scenario. When you enter the base, you will instantly receive 1 or 2 reception clue notifications. MAA won't see the blue icon. It will click on the first infrastructure room (picking up that item), in the meantime, the 2 reception notifications will go away, and the item pickup will come, but that's much faster. 

A good approach would be to: detect the blue icon, if it can be detected, it will click and the logic will continue (as it already happens) in case the blue icon is not recognized, we would need a way to recognize the notification banner (either reception or item collection, just to make sure). Considering it all happens so fast and there aren't many tries to find it, getting a good test is not going to be easy.

**Comment by Viel0320** [comment]
> 5000 is technically enough, but when there is no Reception notification, is definitely too much.
> 
> Anyway, in the worst-case scenario. When you enter the base, you will instantly receive 1 or 2 reception clue notifications. MAA won't see the blue icon. It will click on the first infrastructure room (picking up that item), in the meantime, the 2 reception notifications will go away, and the item pickup will come, but that's much faster.
> 
> A good approach would be to: detect the blue icon, if it can be detected, it will click and the logic will continue (as it already happens) in case the blue icon is not recognized, we would need a way to recognize the notification banner (either reception or item collection, just to make sure). Considering it all happens so fast and there aren't many tries to find it, getting a good test is not going to be easy.
> 
> @zzyyyl Through tasks.json is there a way to implement this type of `if` logic?

 
1 5000ms is the worst case for low-frequency action.

2 Detection would be better, but not economical for me and the blue icon is not always shown.

**Comment by Constrat** [comment]
Personally I would just add the delay in case there's a black notification.
If there is, wait 5000 otherwise, it will either detect the nothing or the notification

**Comment by zzyyyl** [comment]
我觉得这样也行；另外我觉得可能可以做成这样：

InfrastEnteredFlag -> 识别 InfrastNotification -Yes-> ...
InfrastEnteredFlag -> 识别 InfrastNotification -No-> 等2s -> 识别 InfrastNotification -Yes-> ...
InfrastEnteredFlag -> 识别 InfrastNotification -No-> 等2s -> 识别 InfrastNotification -No-> Stop

这里的 if 逻辑可以使用 max_times + post_delay + exceeded_next 实现，或者直接重复（参考 StartButton1 & StartButton1TryAgain）

**Comment by zzyyyl** [comment]
另外 test 没过，多了个逗号

**Comment by Viel0320** [comment]
> 另外 test 没过，多了个逗号

啊，抱歉，已修

**Comment by Viel0320** [comment]
> 我觉得也行，两秒应该不算大问题（大概）
> 
> 改进方案的话，识别不到是因为弹信用挡住，大概有一个跟下图类似的遮挡？
> 
> example
> image
> 
> 那是不是可以直到识别到右上角对应区域是白色的（不是蓝色也不是红色，而是基建背景底色，大概需要截张图）就可以直接 Stop？进基建时候的缩放应该是固定的吧？
> 
> image 上图是我截的 roi = `[1140, 65, 90, 45]` 的”白色区域“模板图（已缩放），裁剪自
> 
> 1920x1080 原图

根据不同的分辨率截图出来的效果也是不同的
下面是1600x900的截图
image

这个方案主要是原issue的启发(并且一直没人提交)，然后是觉得这样是最经济的，代价也完全能接受

**Comment by zzyyyl** [comment]
ci 过了就先合了，改进方案去 #9623 讨论再另开 PR 吧

**Pull request merged**
