### PR TITLE
chore: YoStarKR addition and modification task

### PR DESCRIPTION
**Pull request by HX3N**
Addressed the issue (#8040) by utilizing regex for resolution
Additionally, simplified some "ocrReplace text" instances by employing regex

Tasks that were previously missing, such as 'LevelOfDifficulty' and 'SideStoryReopen', have been added

I tested in all scenarios such as "Operator Squad," "Recruitment in Roguelike," and "Recognition during Battle" to ensure there are no issues
<br>
When tested in reality, many operators (non-mainstream operators) had the issue more than expected
Some of them are recognized as 'Detect model,' but the recognition time is a bit slow
<br>
<details><summary>Logs from actual testing</summary>

```
[2024-01-20 22:48:50.913][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ Castle-3: [ 0, 0, 89, 22 ], score: 0.999960 }] by OCR Rec , cost 12 ms
[2024-01-20 22:48:50.915][TRC][Px3d7dc][Txa29d8] Proceed [{ Castle-3: [ 9, 111, 89, 22 ], score: 0.999960 }]

[2024-01-20 22:36:35.692][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ THRM-EX: [ 0, 0, 103, 20 ], score: 0.935409 }] by OCR Rec , cost 50 ms
[2024-01-20 22:36:35.695][TRC][Px3d7dc][Txa29d8] Proceed [{ THRM-EX: [ 9, 113, 103, 20 ], score: 0.935409 }]

[2024-01-20 22:46:33.601][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ Lancet-2: [ 0, 0, 95, 21 ], score: 0.998541 }] by OCR Rec , cost 13 ms
[2024-01-20 22:46:33.602][TRC][Px3d7dc][Txa29d8] Proceed [{ Lancet-2: [ 9, 111, 95, 21 ], score: 0.998541 }]

[2024-01-20 22:36:34.934][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ Friston-3: [ 0, 0, 99, 22 ], score: 0.981176 }] by OCR Rec , cost 22 ms
[2024-01-20 22:36:34.936][TRC][Px3d7dc][Txa29d8] Proceed [{ Friston-3: [ 9, 111, 99, 22 ], score: 0.981176 }]

[2024-01-20 22:38:17.869][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ Ash: [ 0, 0, 41, 22 ], score: 0.999825 }] by OCR Rec , cost 15 ms
[2024-01-20 22:38:17.871][TRC][Px3d7dc][Txa29d8] Proceed [{ 灰烬: [ 10, 111, 41, 22 ], score: 0.999825 }]

[2024-01-21 00:32:17.413][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ Blitz: [ 0, 0, 51, 22 ], score: 0.956063 }] by OCR Rec , cost 38 ms
[2024-01-21 00:32:17.415][TRC][Pxa5e14][Tx127a14] Proceed [{ 闪击: [ 16, 186, 51, 22 ], score: 0.956063 }]

[2024-01-21 00:24:51.360][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ W: [ 0, 0, 23, 20 ], score: 0.990692 }] by OCR Rec , cost 38 ms
[2024-01-21 00:24:51.362][TRC][Pxa5e14][Tx127a14] Proceed [{ W: [ 17, 188, 23, 20 ], score: 0.990692 }]

[2024-01-20 22:38:19.108][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ 첸V-: [ 0, 0, 179, 23 ], score: 0.755005 }] by OCR Rec , cost 32 ms
[2024-01-20 22:38:19.110][TRC][Px3d7dc][Txa29d8] Proceed [{ 陈: [ 10, 111, 179, 23 ], score: 0.755005 }]

[2024-01-20 22:38:18.472][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ 아르케토y: [ 0, 0, 183, 41 ], score: 0.879307 }] by OCR Rec , cost 16 ms
[2024-01-20 22:38:18.474][TRC][Px3d7dc][Txa29d8] Proceed [{ 空弦: [ 9, 100, 183, 41 ], score: 0.879307 }]

[2024-01-20 22:38:32.962][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ 스즈란A: [ 0, 0, 182, 32 ], score: 0.837381 }] by OCR Rec , cost 13 ms
[2024-01-20 22:38:32.965][TRC][Px3d7dc][Txa29d8] Proceed [{ 铃兰: [ 10, 102, 182, 32 ], score: 0.837381 }]

[2024-01-20 22:39:22.092][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ 사가D-2: [ 0, 0, 182, 30 ], score: 0.670071 }] by OCR Rec , cost 15 ms
[2024-01-20 22:39:22.093][TRC][Px3d7dc][Txa29d8] Proceed [{ 嵯峨: [ 10, 111, 182, 30 ], score: 0.670071 }]

[2024-01-20 22:46:34.189][TRC][Px3d7dc][Txa29d8] asst::WordOcr [{ 시즈294: [ 0, 0, 182, 31 ], score: 0.702248 }] by OCR Rec , cost 20 ms
[2024-01-20 22:46:34.191][TRC][Px3d7dc][Txa29d8] Proceed [{ 推进之王: [ 10, 110, 182, 31 ], score: 0.702248 }]

[2024-01-20 23:41:58.601][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 이프리트2: [ 0, 0, 181, 40 ], score: 0.875860 }] by OCR Rec , cost 30 ms
[2024-01-20 23:41:58.603][TRC][Pxc372c][Txaf7c4] Proceed [{ 伊芙利特: [ 17, 176, 181, 40 ], score: 0.875860 }]

[2024-01-20 23:50:41.374][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 백파이프2: [ 0, 0, 181, 35 ], score: 0.995000 }] by OCR Rec , cost 21 ms
[2024-01-20 23:50:41.375][TRC][Pxc372c][Txaf7c4] Proceed [{ 风笛: [ 17, 175, 181, 35 ], score: 0.995000 }]

[2024-01-21 00:00:53.547][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 실버애쉬2V: [ 0, 0, 180, 38 ], score: 0.809507 }] by OCR Rec , cost 33 ms
[2024-01-21 00:00:53.549][TRC][Pxc372c][Txaf7c4] Proceed [{ 银灰: [ 18, 178, 180, 38 ], score: 0.809507 }]

[2024-01-21 00:02:25.191][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 엑시아.708: [ 0, 0, 182, 31 ], score: 0.630423 }] by OCR Rec , cost 27 ms
[2024-01-21 00:02:25.193][TRC][Pxc372c][Txaf7c4] Proceed [{ 能天使: [ 16, 185, 182, 31 ], score: 0.630423 }]

[2024-01-21 00:02:26.712][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 로사G: [ 0, 0, 181, 41 ], score: 0.640353 }] by OCR Rec , cost 57 ms
[2024-01-21 00:02:26.716][TRC][Pxc372c][Txaf7c4] Proceed [{ 早露: [ 17, 175, 181, 41 ], score: 0.640353 }]

[2024-01-21 00:06:33.754][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 하이모어4: [ 0, 0, 175, 25 ], score: 0.934892 }] by OCR Rec , cost 30 ms
[2024-01-21 00:06:33.755][TRC][Pxc372c][Txaf7c4] Proceed [{ 海沫: [ 17, 185, 175, 25 ], score: 0.934892 }]

[2024-01-21 00:09:27.852][TRC][Pxc372c][Txaf7c4] asst::WordOcr [{ 안드레아나A—: [ 0, 0, 182, 41 ], score: 0.959721 }] by OCR Rec , cost 26 ms
[2024-01-21 00:09:27.854][TRC][Pxc372c][Txaf7c4] Proceed [{ 安哲拉: [ 16, 175, 182, 41 ], score: 0.959721 }]

[2024-01-21 00:13:55.073][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 에이프릴I4: [ 0, 0, 182, 35 ], score: 0.936651 }] by OCR Rec , cost 32 ms
[2024-01-21 00:13:55.075][TRC][Pxa5e14][Tx127a14] Proceed [{ 四月: [ 16, 175, 182, 35 ], score: 0.936651 }]

[2024-01-21 00:18:44.832][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 로프46: [ 0, 0, 181, 34 ], score: 0.881785 }] by OCR Rec , cost 73 ms
[2024-01-21 00:18:44.835][TRC][Pxa5e14][Tx127a14] Proceed [{ 暗索: [ 17, 182, 181, 34 ], score: 0.881785 }]

[2024-01-21 00:18:45.667][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 프라마닉스72: [ 0, 0, 172, 25 ], score: 0.969629 }] by OCR Rec , cost 57 ms
[2024-01-21 00:18:45.670][TRC][Pxa5e14][Tx127a14] Proceed [{ 初雪: [ 17, 185, 172, 25 ], score: 0.969629 }]

[2024-01-21 00:18:46.579][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 사가2C—/: [ 0, 0, 181, 41 ], score: 0.811186 }] by OCR Rec , cost 40 ms
[2024-01-21 00:18:46.585][TRC][Pxa5e14][Tx127a14] Proceed [{ 嵯峨: [ 17, 175, 181, 41 ], score: 0.811186 }]

[2024-01-21 00:18:47.420][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 베나_68: [ 0, 0, 181, 31 ], score: 0.623986 }] by OCR Rec , cost 29 ms
[2024-01-21 00:18:47.422][TRC][Pxa5e14][Tx127a14] Proceed [{ 贝娜: [ 17, 185, 181, 31 ], score: 0.623986 }]

[2024-01-21 00:18:50.097][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 에단76: [ 0, 0, 181, 24 ], score: 0.787959 }] by OCR Rec , cost 46 ms
[2024-01-21 00:18:50.100][TRC][Pxa5e14][Tx127a14] Proceed [{ 伊桑: [ 17, 186, 181, 24 ], score: 0.787959 }]

[2024-01-21 00:20:40.904][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 미즈키74: [ 0, 0, 181, 41 ], score: 0.737733 }] by OCR Rec , cost 28 ms
[2024-01-21 00:20:40.906][TRC][Pxa5e14][Tx127a14] Proceed [{ 水月: [ 17, 175, 181, 41 ], score: 0.737733 }]

[2024-01-21 00:20:41.750][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 블레미샤인7: [ 0, 0, 181, 35 ], score: 0.982148 }] by OCR Rec , cost 20 ms
[2024-01-21 00:20:41.751][TRC][Pxa5e14][Tx127a14] Proceed [{ 瑕光: [ 17, 175, 181, 35 ], score: 0.982148 }]

[2024-01-21 00:26:47.048][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 칸타빌레7: [ 0, 0, 181, 35 ], score: 0.878835 }] by OCR Rec , cost 18 ms
[2024-01-21 00:26:47.049][TRC][Pxa5e14][Tx127a14] Proceed [{ 晓歌: [ 17, 175, 181, 35 ], score: 0.878835 }]

[2024-01-21 00:26:48.585][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 샤마르68: [ 0, 0, 181, 35 ], score: 0.703558 }] by OCR Rec , cost 40 ms
[2024-01-21 00:26:48.587][TRC][Pxa5e14][Tx127a14] Proceed [{ 巫恋: [ 17, 175, 181, 35 ], score: 0.703558 }]

[2024-01-21 00:26:49.662][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 텍사스—K: [ 0, 0, 181, 30 ], score: 0.813349 }] by OCR Rec , cost 21 ms
[2024-01-21 00:26:49.664][TRC][Pxa5e14][Tx127a14] Proceed [{ 德克萨斯: [ 17, 186, 181, 30 ], score: 0.813349 }]

[2024-01-21 00:26:55.258][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 파이어휘슬N: [ 0, 0, 179, 29 ], score: 0.892274 }] by OCR Rec , cost 23 ms
[2024-01-21 00:26:55.259][TRC][Pxa5e14][Tx127a14] Proceed [{ 火哨: [ 17, 181, 179, 29 ], score: 0.892274 }]

[2024-01-21 00:29:21.526][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 사일런스4C: [ 0, 0, 181, 30 ], score: 0.944694 }] by OCR Rec , cost 15 ms
[2024-01-21 00:29:21.527][TRC][Pxa5e14][Tx127a14] Proceed [{ 赫默: [ 17, 186, 181, 30 ], score: 0.944694 }]

[2024-01-21 00:29:24.415][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 실론L: [ 0, 0, 180, 41 ], score: 0.933488 }] by OCR Rec , cost 39 ms
[2024-01-21 00:29:24.417][TRC][Pxa5e14][Tx127a14] Proceed [{ 锡兰: [ 18, 175, 180, 41 ], score: 0.933488 }]

[2024-01-21 00:30:48.877][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 무스8.: [ 0, 0, 181, 35 ], score: 0.868841 }] by OCR Rec , cost 17 ms
[2024-01-21 00:30:48.880][TRC][Pxa5e14][Tx127a14] Proceed [{ 慕斯: [ 17, 181, 181, 35 ], score: 0.868841 }]

[2024-01-21 00:30:50.376][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 클릭X: [ 0, 0, 174, 30 ], score: 0.791121 }] by OCR Rec , cost 23 ms
[2024-01-21 00:30:50.377][TRC][Pxa5e14][Tx127a14] Proceed [{ 卡达: [ 17, 185, 174, 30 ], score: 0.791121 }]

[2024-01-21 00:32:12.661][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 리드_K: [ 0, 0, 182, 39 ], score: 0.869483 }] by OCR Rec , cost 33 ms
[2024-01-21 00:32:12.662][TRC][Pxa5e14][Tx127a14] Proceed [{ 苇草: [ 16, 177, 182, 39 ], score: 0.869483 }]

[2024-01-21 00:32:13.500][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 스노우상트/4: [ 0, 0, 181, 36 ], score: 0.777775 }] by OCR Rec , cost 26 ms
[2024-01-21 00:32:13.502][TRC][Pxa5e14][Tx127a14] Proceed [{ 雪雉: [ 17, 180, 181, 36 ], score: 0.777775 }]

[2024-01-21 00:32:16.704][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 크루아상4,: [ 0, 0, 181, 39 ], score: 0.912369 }] by OCR Rec , cost 27 ms
[2024-01-21 00:32:16.706][TRC][Pxa5e14][Tx127a14] Proceed [{ 可颂: [ 17, 177, 181, 39 ], score: 0.912369 }]

[2024-01-21 00:34:28.770][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 플룸———4: [ 0, 0, 181, 24 ], score: 0.915708 }] by OCR Rec , cost 59 ms
[2024-01-21 00:34:28.772][TRC][Pxa5e14][Tx127a14] Proceed [{ 翎羽: [ 17, 185, 181, 24 ], score: 0.915708 }]

[2024-01-21 00:34:34.767][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 파인콘C2: [ 0, 0, 172, 29 ], score: 0.905498 }] by OCR Rec , cost 18 ms
[2024-01-21 00:34:34.769][TRC][Pxa5e14][Tx127a14] Proceed [{ 松果: [ 17, 181, 172, 29 ], score: 0.905498 }]

[2024-01-21 00:36:13.441][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 미드나이트E: [ 0, 0, 181, 29 ], score: 0.881680 }] by OCR Rec , cost 44 ms
[2024-01-21 00:36:13.443][TRC][Pxa5e14][Tx127a14] Proceed [{ 月见夜: [ 17, 186, 181, 29 ], score: 0.881680 }]

[2024-01-21 00:36:14.880][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 비글—7: [ 0, 0, 181, 31 ], score: 0.743975 }] by OCR Rec , cost 47 ms
[2024-01-21 00:36:14.883][TRC][Pxa5e14][Tx127a14] Proceed [{ 米格鲁: [ 17, 185, 181, 31 ], score: 0.743975 }]

[2024-01-21 00:36:18.680][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 라바—4: [ 0, 0, 174, 27 ], score: 0.924112 }] by OCR Rec , cost 29 ms
[2024-01-21 00:36:18.682][TRC][Pxa5e14][Tx127a14] Proceed [{ 炎熔: [ 17, 186, 174, 27 ], score: 0.924112 }]

[2024-01-21 00:37:29.987][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 새비지_K/: [ 0, 0, 174, 35 ], score: 0.772221 }] by OCR Rec , cost 16 ms
[2024-01-21 00:37:29.988][TRC][Pxa5e14][Tx127a14] Proceed [{ 暴行: [ 17, 175, 174, 35 ], score: 0.772221 }]

[2024-01-21 00:38:47.709][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 위슬래시,A: [ 0, 0, 181, 41 ], score: 0.845034 }] by OCR Rec , cost 49 ms
[2024-01-21 00:38:47.712][TRC][Pxa5e14][Tx127a14] Proceed [{ 鞭刃: [ 17, 175, 181, 41 ], score: 0.845034 }]

[2024-01-21 00:39:53.233][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 비질3: [ 0, 0, 181, 32 ], score: 0.787499 }] by OCR Rec , cost 19 ms
[2024-01-21 00:39:53.234][TRC][Pxa5e14][Tx127a14] Proceed [{ 伺夜: [ 17, 178, 181, 32 ], score: 0.787499 }]

[2024-01-21 00:41:27.378][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 카니팔라트—o: [ 0, 0, 180, 27 ], score: 0.901960 }] by OCR Rec , cost 53 ms
[2024-01-21 00:41:27.382][TRC][Pxa5e14][Tx127a14] Proceed [{ 雪绒: [ 18, 186, 180, 27 ], score: 0.901960 }]

[2024-01-21 00:44:41.293][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 메테오4: [ 0, 0, 181, 30 ], score: 0.961917 }] by OCR Rec , cost 30 ms
[2024-01-21 00:44:41.295][TRC][Pxa5e14][Tx127a14] Proceed [{ 流星: [ 17, 186, 181, 30 ], score: 0.961917 }]

[2024-01-21 00:44:47.332][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 듀나A—-: [ 0, 0, 170, 24 ], score: 0.818028 }] by OCR Rec , cost 18 ms
[2024-01-21 00:44:47.334][TRC][Pxa5e14][Tx127a14] Proceed [{ 坚雷: [ 17, 186, 170, 24 ], score: 0.818028 }]

[2024-01-21 00:46:21.873][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 로베르타.D: [ 0, 0, 181, 35 ], score: 0.903372 }] by OCR Rec , cost 27 ms
[2024-01-21 00:46:21.876][TRC][Pxa5e14][Tx127a14] Proceed [{ 罗比菈塔: [ 17, 175, 181, 35 ], score: 0.903372 }]

[2024-01-21 00:46:21.101][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 포덴코4: [ 0, 0, 181, 37 ], score: 0.808683 }] by OCR Rec , cost 25 ms
[2024-01-21 00:46:21.105][TRC][Pxa5e14][Tx127a14] Proceed [{ 波登可: [ 17, 175, 181, 37 ], score: 0.808683 }]

[2024-01-21 00:46:22.636][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 애시드드롭2)): [ 0, 0, 173, 30 ], score: 0.891201 }] by OCR Rec , cost 18 ms
[2024-01-21 00:46:22.639][TRC][Pxa5e14][Tx127a14] Proceed [{ 酸糖: [ 17, 180, 173, 30 ], score: 0.891201 }]

[2024-01-21 00:46:25.001][TRC][Pxa5e14][Tx127a14] asst::WordOcr [{ 인디고_MC: [ 0, 0, 181, 41 ], score: 0.772695 }] by OCR Rec , cost 28 ms
[2024-01-21 00:46:25.005][TRC][Pxa5e14][Tx127a14] Proceed [{ 深靛: [ 17, 175, 181, 41 ], score: 0.772695 }]
```
</details>
<br><br>

[overalltest.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14003165/tasksjsontest.log)

### CODE REVIEW

**Comment by Constrat** [comment]
There's a lot of different changes.

**Comment by HX3N** [comment]
> There's a lot of different changes.

Would it be better to separate the PR into a part about modifying “ocrReplace” and a part about adding new “tasks”?

**Comment by Constrat** [comment]
Yeah preferably.

**Comment by HX3N** [comment]
I will separate the pull request and upload it again.

**Pull request closed without merging**
