### PR TITLE
feat: dotnetCore8.0

### PR DESCRIPTION
**Pull request by ABA2396**

### CODE REVIEW

**Comment by SherkeyXD** [comment]
qodana是不是不支持dotnet8啊（

**Comment by Constrat** [comment]
qodana hates 8:
> via [JetBrains/Qodana](https://www.jetbrains.com/help/qodana/qodana-dotnet.html#Analyze+a+project+locally)

Qodana for .NET is suitable for analyzing .NET Core projects and provides the following SDK versions:
3.0.103
6.0.405
7.0.102

**Comment by SherkeyXD** [comment]
Waiting for https://github.com/actions/runner-images/issues/8797

**Comment by SherkeyXD** [comment]
所以还改不改构建流程啊（

**Comment by zzyyyl** [comment]
改，都可以改

**Comment by SherkeyXD** [comment]
但是我不会写makefile（摊手
快摇人来写（

**Comment by ABA2396** [comment]
#7554

**Pull request closed without merging**
